/*
  # Add Ireland Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Irish passport holders traveling to all 51 active destinations.

  ## Ireland Passport Profile
  - Top 5 most powerful passport globally
  - EU member but NOT in Schengen Area (uses Common Travel Area with UK)
  - Separate visa policies for non-Schengen travel
  - Visa-free or ETA access to 185+ destinations

  ## Key Distinctions
  - Ireland is EU but NOT Schengen: still has freedom of movement in EU/EEA
  - Common Travel Area (CTA) with UK: no visa/passport needed for UK travel
  - Irish citizens need Schengen rules when visiting Schengen countries as tourists (90/180)
    BUT as EU citizens have unlimited stay rights for residency

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
-- EU/EEA countries - unlimited freedom of movement as EU citizen
(gen_random_uuid(), 'ireland', 'austria', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Austria are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.bmeia.gv.at', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Austria as EU member. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'belgium', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Belgium are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://dofi.ibz.be', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Belgium. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'croatia', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Croatia are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://mup.gov.hr', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Croatia. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'czech-republic', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Czech Republic are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.mvcr.cz', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Czech Republic. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'denmark', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Denmark are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Denmark. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'finland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Finland are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Finland. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'france', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and France are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://france-visas.gouv.fr', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in France. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'germany', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Germany are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.bmi.bund.de', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Germany. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'greece', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Greece are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.ypes.gr', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Greece. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'hungary', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Hungary are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.kormany.hu', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Hungary. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'italy', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Italy are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.interno.gov.it', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Italy. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'netherlands', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Netherlands are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://ind.nl', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Netherlands. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'norway', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland is EU; Norway is EEA. Full freedom of movement under EEA.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Irish citizens have full right to enter, reside, and work in Norway under EEA agreement.'),
(gen_random_uuid(), 'ireland', 'poland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Poland are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Poland. Large Irish diaspora in Poland.'),
(gen_random_uuid(), 'ireland', 'portugal', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Portugal are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.sef.pt', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Portugal. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'romania', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Romania are both EU members. Romania joined Schengen in 2024.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Romania. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'spain', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Spain are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.interior.gob.es', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Spain. Large Irish community. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'sweden', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland and Sweden are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Irish citizens have unrestricted right to enter, reside, and work in Sweden. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'ireland', 'switzerland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Ireland is EU/EEA; Switzerland is EEA associate with bilateral agreements.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.sem.admin.ch', '2026-02-24', 'Irish citizens have full right to enter, reside, and work in Switzerland under EEA agreement.'),
-- Common Travel Area - UK (no passport needed, just ID)
(gen_random_uuid(), 'ireland', 'united-kingdom', 'visa_free', 'CTA', NULL, NULL, 'Unlimited stay. Ireland and UK share the Common Travel Area - no visa or passport controls.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.gov.uk/government/publications/common-travel-area-guidance', '2026-02-24', 'Irish citizens have unrestricted right to live and work in UK under the Common Travel Area. No passport controls between Ireland and UK. Pre-dates EU membership.'),
-- Visa-free destinations
(gen_random_uuid(), 'ireland', 'argentina', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Extendable through Dirección Nacional de Migraciones.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Irish passport holders enjoy visa-free access to Argentina.'),
(gen_random_uuid(), 'ireland', 'australia', 'evisa', 'eVisitor', 90, NULL, '90 days per visit within 12-month validity. Multiple entries permitted.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651', '2026-02-24', 'Irish passport holders eligible for free eVisitor visa (subclass 651). Apply online before travel. Strong Irish-Australian ties.'),
(gen_random_uuid(), 'ireland', 'brazil', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Extendable once for additional 90 days.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Irish passport holders enjoy visa-free access to Brazil.'),
(gen_random_uuid(), 'ireland', 'canada', 'evisa', 'eTA', 180, NULL, 'Up to 6 months per entry. Immigration officer determines duration at port of entry.', NULL, 'valid_for_stay', 'may_be_requested', 'required', 'may_be_requested', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html', '2026-02-24', 'eTA required for Irish citizens arriving by air. CAD $7 fee, valid 5 years. Large Irish diaspora in Canada.'),
(gen_random_uuid(), 'ireland', 'chile', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Irish passport holders enjoy visa-free access to Chile.'),
(gen_random_uuid(), 'ireland', 'colombia', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Extension possible through Migración Colombia.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Irish passport holders enjoy visa-free access to Colombia.'),
(gen_random_uuid(), 'ireland', 'egypt', 'visa_on_arrival', 'VOA or eVisa', 30, NULL, '30 days single/multiple entry. Extensions available through Mogamma in Cairo.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Visa on arrival (USD $25) or eVisa online (USD $25). eVisa recommended to avoid queues.'),
(gen_random_uuid(), 'ireland', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days. eBusiness: up to 180 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Irish passport holders must obtain eVisa before travel. Apply at least 4 days before.'),
(gen_random_uuid(), 'ireland', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available at major airports and seaports. Single entry, tourist only.'),
(gen_random_uuid(), 'ireland', 'israel', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Entry card issued on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Irish passport holders enjoy visa-free access to Israel. Security screening at entry is thorough.'),
(gen_random_uuid(), 'ireland', 'japan', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. Cannot engage in paid activities.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Irish passport holders enjoy visa-free access under bilateral agreement.'),
(gen_random_uuid(), 'ireland', 'malaysia', 'visa_free', NULL, 90, NULL, '90 days per entry. Extendable at immigration department.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Irish passport holders enjoy visa-free access to Malaysia for up to 90 days.'),
(gen_random_uuid(), 'ireland', 'mexico', 'visa_free', NULL, 180, NULL, 'Up to 180 days. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Irish passport holders enjoy visa-free access to Mexico.'),
(gen_random_uuid(), 'ireland', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Irish passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'ireland', 'new-zealand', 'evisa', 'NZeTA', 90, NULL, '90 days per visit within 18-month validity. Multiple entries permitted.', 3, '3_months_beyond_departure', 'required', 'required', 'may_be_requested', 'https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/nzeta', '2026-02-24', 'NZeTA required before travel. NZD $17 via app or NZD $23 via website. IVL of NZD $35 also required. Large Irish community in NZ.'),
(gen_random_uuid(), 'ireland', 'nigeria', 'evisa', 'eVisa on Arrival', 90, NULL, '90 days tourist/business visa. Single or multiple entry.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://portal.immigration.gov.ng', '2026-02-24', 'Irish passport holders must obtain eVisa before travel. USD $160 fee. Yellow fever vaccination certificate mandatory.'),
(gen_random_uuid(), 'ireland', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry. Extensions possible through Superintendencia Nacional de Migraciones.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Irish passport holders enjoy visa-free access to Peru. Yellow fever vaccination recommended for jungle regions.'),
(gen_random_uuid(), 'ireland', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable up to 36 months total.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Irish passport holders receive 30-day visa-free entry. Extensions available through Bureau of Immigration.'),
(gen_random_uuid(), 'ireland', 'qatar', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa waiver granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Irish passport holders enjoy visa-free access under Qatar''s visa waiver program.'),
(gen_random_uuid(), 'ireland', 'russia', 'evisa', 'eVisa', 16, NULL, 'eVisa: 16 days for specific regions. Single entry only.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://electronic-visa.kdmid.ru', '2026-02-24', 'eVisa for select regions. Traditional visa required elsewhere. Travel advisory in place.'),
(gen_random_uuid(), 'ireland', 'saudi-arabia', 'evisa', 'eVisa', 90, 180, '90 days per visit, up to 180 days per year. Multiple entry.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visa.visitsaudi.com', '2026-02-24', 'Tourist eVisa available. SAR 300 + insurance fee. Respect local laws and dress code.'),
(gen_random_uuid(), 'ireland', 'singapore', 'visa_free', NULL, 90, NULL, '90 days per entry. Entry stamp issued on arrival.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Irish passport holders enjoy visa-free access to Singapore.'),
(gen_random_uuid(), 'ireland', 'south-africa', 'visa_free', NULL, 90, NULL, '90 days per calendar year. Visitor''s visa issued at port of entry.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'Irish passport holders enjoy visa-free access. Must have at least 2 blank pages in passport. Large Irish-South African community.'),
(gen_random_uuid(), 'ireland', 'south-korea', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. K-ETA electronic authorization recommended.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.k-eta.go.kr', '2026-02-24', 'Irish passport holders enjoy visa-free access. K-ETA (KRW 10,000) recommended for smoother entry.'),
(gen_random_uuid(), 'ireland', 'thailand', 'visa_free', NULL, 60, NULL, '60 days visa exemption. Extendable once for 30 days at immigration office.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Irish passport holders enjoy 60-day visa-free entry (extended from 30 days in 2024).'),
(gen_random_uuid(), 'ireland', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Irish passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Check official advisories before travel.'),
(gen_random_uuid(), 'ireland', 'united-arab-emirates', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'Irish passport holders enjoy visa-free access. Major hub for business and tourism.'),
(gen_random_uuid(), 'ireland', 'united-states', 'evisa', 'ESTA', 90, NULL, '90 days for tourism/business under Visa Waiver Program. No extensions permitted.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://esta.cbp.dhs.gov', '2026-02-24', 'ESTA required under Visa Waiver Program. USD $21 fee, valid 2 years. Large Irish diaspora in USA.'),
(gen_random_uuid(), 'ireland', 'vietnam', 'evisa', 'eVisa', 90, NULL, '90 days single or multiple entry. Extendable within Vietnam.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Irish passport holders can obtain eVisa (USD $25) valid for 90 days. Apply online before travel.'),
(gen_random_uuid(), 'ireland', 'china', 'visa_required', NULL, NULL, NULL, 'Visa required. Tourist (L) visa typically 30-90 days. Transit exemptions in select cities.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China requires visa for Irish passport holders. Apply through Chinese Visa Application Service Center.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
