/*
  # Update UK Blog Posts with Correct Content Format

  Rewrites the content JSON for all 5 UK visa blog posts to use the correct
  BlogContentBlock schema: types intro, section (with list array), faq, callout.
  This ensures the blog post detail page renders all content correctly.
*/

UPDATE blog_posts SET content = '[
  {"type":"intro","text":"The United Kingdom has always been one of the most natural international destinations for Americans — shared language, cultural familiarity, strong business ties, and a bucket list that ranges from the streets of London to the Scottish Highlands. But UK entry rules for US citizens changed significantly in 2025, and 2026 has brought further updates that catch many travelers off guard.\n\nThe single most important thing to know: US citizens no longer enter the UK visa-free without any prior formality. Since April 2, 2025, all Americans traveling to the UK for short stays must hold an approved Electronic Travel Authorisation (ETA) before boarding any transport to Britain. Without it, you can be denied boarding before you even leave the United States."},
  {"type":"callout","calloutType":"warn","text":"Critical 2026 update: The UK ETA fee increased from £10 to £16 per person effective February 25, 2026. Every traveler — including babies and children — needs their own ETA. The fee is non-refundable even if denied."},
  {"type":"section","heading":"Do US Citizens Need a Visa for the UK?","text":"For short stays of up to 6 months — tourism, family visits, business meetings, conferences, short-term study — US citizens do not need a traditional visa. However, since April 2025, they do need a UK Electronic Travel Authorisation (ETA): a mandatory pre-travel digital permission linked to your passport. Think of it as the UK equivalent of the US ESTA system."},
  {"type":"section","heading":"The UK ETA: Key Facts (2026)","list":["Cost: £16 per person (increased from £10 on February 25, 2026)","Valid for: 2 years or until your passport expires — whichever comes first","Entries: Multiple — unlimited trips during validity","Each visit: Up to 6 months per entry","Processing: Usually minutes; allow up to 3 business days","Application: Online via the official UK government ETA app or GOV.UK website","Non-refundable: even if denied"]},
  {"type":"section","heading":"What the ETA Does Not Cover","text":"The ETA covers short visits only. It does not allow you to work for a UK employer, study long-term beyond 6 months, access public funds, or settle in the UK permanently. If your plans include working, studying, or moving to the UK, you need a specific visa."},
  {"type":"section","heading":"Long-Stay and Residency Options for Americans","list":["Skilled Worker visa — minimum salary £41,700 per year as of 2026","UK Student Visa — requires unconditional university offer and proof of financial means","Family Visa — for joining a UK citizen or settled person","Indefinite Leave to Remain (ILR) — permanent residence after 5 continuous years"]},
  {"type":"faq","items":[{"q":"Do I need to print my ETA confirmation?","a":"No. Your ETA is electronically linked to your passport. You do not need to carry any documentation — just travel with the same passport you used when applying. The airline and UK border systems check it automatically when they scan your passport."},{"q":"Can I work remotely for my US employer while visiting the UK on an ETA?","a":"This is a gray area. The UK government allows permitted paid engagement for short, incidental periods, but using a visit as a de facto relocation while working remotely full-time is not in the spirit of visitor rules. For extended remote-work stays, the correct route is a work visa."},{"q":"My ETA was denied. What now?","a":"ETA refusals cannot be appealed. You can reapply if the refusal was based on an error, or apply for a Standard Visitor Visa, which involves a more formal assessment with supporting documents and human review."},{"q":"How early should I apply for my UK ETA?","a":"The UK government advises applying at least 72 hours before travel, but most applications are decided within minutes. Applying several weeks in advance removes any last-minute stress."}]}
]'::jsonb
WHERE slug = 'uk-visa-for-us-citizens';

UPDATE blog_posts SET content = '[
  {"type":"intro","text":"If you have not been to the UK since before April 2025, there is a new step in your pre-trip checklist. Americans now need a UK Electronic Travel Authorisation (ETA) before boarding any transport to Britain — flight, ferry, or Eurostar train.\n\nIt is not a visa. It does not change what you can do as a visitor. It will not stamp your passport or appear in any document you carry. But it is now a hard legal requirement, and airlines are checking for it. Arrive without one, and you may not be allowed to board."},
  {"type":"section","heading":"What Is the UK ETA?","text":"The UK Electronic Travel Authorisation is a pre-entry digital clearance system introduced by the UK Home Office. It is electronically linked to your passport — a background check that happens before you arrive, rather than at the border. The concept is identical to the US ESTA. You answer a short set of questions; if approved, a digital permission is attached to your passport record. Airlines verify it automatically at check-in."},
  {"type":"section","heading":"Key Facts: UK ETA for US Citizens (2026)","list":["Required since: April 2, 2025 for US citizens","Fee: £16 per person (increased from £10 on 25 Feb 2026)","Valid for: 2 years or until passport expires — whichever is sooner","Entries: Multiple — unlimited trips during validity","Stay per visit: Up to 6 months","Processing time: Usually minutes; allow up to 3 business days","Apply via: Official UK ETA app or GOV.UK website","Refundable: No — even if denied","Applies to children: Yes — every traveler needs their own ETA, including infants"]},
  {"type":"section","heading":"What Changed in 2026","list":["Fee increased from £10 to £16 per person effective February 25, 2026","Dual British-American citizens must now travel on their British passport — they cannot use a US passport and obtain an ETA as a workaround"]},
  {"type":"section","heading":"How to Apply: Step by Step","list":["Use the official UK ETA app (iOS/Android) or GOV.UK — avoid third-party sites charging more","Scan your US passport using your phone camera","Take a live selfie for identity verification","Answer questions about your travel plans and background honestly","Pay £16 by card, Apple Pay, or Google Pay","Wait for decision — usually minutes, up to 3 business days","Travel with the same passport you applied with — no printed document needed"]},
  {"type":"callout","calloutType":"tip","text":"Apply via the official UK ETA app or GOV.UK — both are free to use. Third-party sites often charge significantly more for the same service. Make sure the URL ends in .gov.uk if using the website."},
  {"type":"section","heading":"What the ETA Permits and Does Not Permit","list":["Permitted: Tourism, leisure, holidays","Permitted: Visiting family and friends","Permitted: Business meetings, conferences, negotiations (not working for a UK employer)","Permitted: Short-term study up to 6 months","Permitted: Transit through UK airports","Not permitted: Taking up paid employment with a UK employer","Not permitted: Working as self-employed in the UK market","Not permitted: Studying more than 6 months","Not permitted: Settling in the UK"]},
  {"type":"faq","items":[{"q":"If I get a new passport, do I need a new ETA?","a":"Yes. Your ETA is linked to the specific passport you applied with. If your passport expires, is renewed, or is replaced, you need to apply for a new ETA linked to your new document."},{"q":"Does every member of my family need an ETA?","a":"Yes. Every traveler — including babies, toddlers, and children — needs their own individual ETA. A family of four pays 4 × £16 = £64."},{"q":"Do I need an ETA if I am just transiting through a UK airport?","a":"Yes — as of April 2025, even airside transit through UK airports requires an ETA for US citizens, with very limited exceptions at Manchester and Heathrow for non-border-control transit."},{"q":"Can I apply for the ETA when I am already in the UK?","a":"No. The ETA must be obtained before you travel. You cannot apply once you are already in the UK."}]}
]'::jsonb
WHERE slug = 'uk-eta-for-us-citizens';

UPDATE blog_posts SET content = '[
  {"type":"intro","text":"The vast majority of Americans visiting the UK in 2026 will do so using the UK ETA — the £16 digital travel authorisation that covers short stays for tourism, business, family visits, and transit. But there is a smaller group of US citizens for whom the ETA is not the right route, or is not an option at all.\n\nIf your ETA was refused, if you have a criminal history, if you have had previous UK immigration issues, or if you want the flexibility of a long-term multi-entry visa — the UK Standard Visitor Visa is what you need."},
  {"type":"section","heading":"What Is the UK Standard Visitor Visa?","text":"The Standard Visitor Visa is the UK formal short-stay visa for people who need or want a visa rather than an ETA. It covers the same activities — tourism, family visits, business meetings, short-term study — and allows stays of up to 6 months per visit. Unlike the ETA, which is an automated digital check, a Standard Visitor Visa involves a formal application with supporting documents, a biometric appointment at a UK Visa Application Centre, and a decision by a UK Visas and Immigration caseworker."},
  {"type":"section","heading":"When Do US Citizens Need a Standard Visitor Visa?","list":["Your ETA application was refused","You have a criminal conviction","You have a history of overstaying or immigration violations in the UK or elsewhere","You have been previously deported or banned from the UK","You want a long-term visitor visa — 2-year, 5-year, or 10-year multi-entry options are available","Your circumstances are complex and you want human caseworker review rather than automated processing"]},
  {"type":"callout","calloutType":"info","text":"Long-term visitor visas: If you travel to the UK regularly for business, a 2-year, 5-year, or 10-year Standard Visitor Visa can be more cost-effective than applying for a new ETA every two years. These multi-entry visas allow multiple stays of up to 6 months each throughout their validity."},
  {"type":"section","heading":"Document Checklist","list":["Valid US passport — must cover your full stay; bring previous passports showing UK entry history","Completed online application form via the UKVI portal","Application fee: £115 (6 months), £400 (2 years), £771 (5 years), £963 (10 years)","Biometric enrollment at a UK Visa Application Centre in the US (New York, LA, Washington DC, Chicago, Houston, and others)","Proof of financial means — recent bank statements","Proof of employment or income — employer letter, pay stubs, or self-employment evidence","Proof of accommodation — hotel bookings or host invitation letter","Return or onward travel ticket","Evidence of ties to the US — employment, property, family commitments"]},
  {"type":"section","heading":"Processing Times","list":["Standard processing: approximately 3 weeks from biometric appointment","Priority processing (additional fee): approximately 5 business days","Super priority (same/next day): not available for US-based applicants"]},
  {"type":"faq","items":[{"q":"How much does a UK Standard Visitor Visa cost for Americans?","a":"For a standard 6-month visitor visa: £115 (approximately $145 USD). For a 2-year visa: £400. For 5 years: £771. For 10 years: £963. All fees are non-refundable."},{"q":"Can I work in the UK on a Standard Visitor Visa?","a":"No. The Standard Visitor Visa explicitly prohibits working for a UK employer or engaging in self-employment in the UK. For work, you need a UK work visa."},{"q":"If I have an ETA, do I also need a Standard Visitor Visa?","a":"No — for most Americans visiting short-term, the ETA is sufficient. The Standard Visitor Visa is an alternative for those who cannot get an ETA or want options like a 10-year visa that the ETA does not provide."}]}
]'::jsonb
WHERE slug = 'uk-standard-visitor-visa-us-citizens';

UPDATE blog_posts SET content = '[
  {"type":"intro","text":"The United Kingdom remains one of the most attractive destinations in the world for American professionals — from finance in London to tech in Manchester, creative industries in Edinburgh, and healthcare across the country.\n\nThe UK points-based immigration system, introduced in 2021, treats all non-UK nationals equally — including Americans. There is no special relationship that gives US citizens a fast track to UK employment. What US citizens do have: English proficiency is assumed, no TB test is required, and smartphone biometrics replace in-person consulate visits for most."},
  {"type":"section","heading":"The UK Sponsorship-Based Work System","text":"The most important thing to understand: UK work immigration is sponsorship-driven. For the main work routes, you cannot apply on your own — a UK employer must hold a government-approved sponsorship licence and agree to sponsor your specific role. This is not a barrier for most skilled professionals; thousands of UK employers hold licences. But your job search and visa strategy need to run in parallel from the start."},
  {"type":"section","heading":"Skilled Worker Visa — Key Requirements (2026)","list":["Job offer from a UK employer holding a valid sponsorship licence","Minimum salary: £41,700 per year or the official going rate — whichever is higher","Skill level: RQF Level 6 (roughly equivalent to a bachelor degree)","US citizens are automatically exempt from the English language requirement","Certificate of Sponsorship (CoS) issued by your employer before you apply","Visa fee: £769 (up to 3 years) or £1,519 (more than 3 years)","Immigration Health Surcharge: £1,035 per year — paid upfront for the full visa duration","Route to ILR after 5 years of continuous qualifying residence"]},
  {"type":"section","heading":"Other Work Visa Routes for Americans","list":["Health and Care Worker visa — lower fees (£304 for 3 years), full IHS exemption; for qualified clinical professionals","Global Talent visa — no job offer or sponsorship required; requires endorsement as a recognized leader in your field","Youth Mobility Scheme — for ages 18-30: 2-year stay, any employer, no salary threshold, no sponsorship required","Innovator Founder visa — for entrepreneurs with an endorsed innovative and viable business plan"]},
  {"type":"callout","calloutType":"tip","text":"Practical advantages for US citizens: No English language test required. No tuberculosis certificate needed. Most Americans can use the UK Immigration ID Check app for smartphone biometrics instead of visiting a visa application center in person."},
  {"type":"section","heading":"Comparison: Key Work Visa Routes (2026)","list":["Skilled Worker: needs job offer, £41,700+ salary, any age, leads to ILR in 5 years","Health and Care Worker: needs job offer, role-specific salary, any age, leads to ILR in 5 years","Global Talent: no job offer needed, no salary threshold, any age, leads to ILR in 3-5 years","Youth Mobility Scheme: no job offer needed, no salary threshold, ages 18-30, does not lead directly to ILR","Innovator Founder: no job offer needed, no salary threshold, any age, leads to ILR in 3 years"]},
  {"type":"faq","items":[{"q":"Can I freelance or work for myself on a UK Skilled Worker visa?","a":"No. The Skilled Worker visa ties you to your sponsoring employer. Self-employment and freelancing are not permitted. The Global Talent and Innovator Founder visas offer more flexibility for self-employed professionals and entrepreneurs."},{"q":"What happens if I lose my job on a Skilled Worker visa?","a":"Your sponsor must notify the Home Office when your employment ends. You will normally be given approximately 60 days to find a new sponsor, switch to a different visa, or leave the UK."},{"q":"Can my spouse or partner join me in the UK on a work visa?","a":"Yes. Most UK work visa routes allow dependants — spouses, civil partners, and children. Dependants on Skilled Worker visas generally receive open work permission, meaning they can work for any UK employer without needing separate sponsorship."}]}
]'::jsonb
WHERE slug = 'uk-work-visa-for-americans';

UPDATE blog_posts SET content = '[
  {"type":"intro","text":"For many Americans, moving to the United Kingdom is a life goal that sits somewhere between deeply romantic and genuinely practical. The appeal is real — a world-class city in London, extraordinary quality of life in places like Edinburgh or Bristol, strong employment in finance, tech, and healthcare, and a cultural familiarity that makes the transition less jarring than many other international moves.\n\nBut the logistics are more involved than booking a one-way flight. The UK system is tightly structured around purpose — why you are coming, what you will do there, and how you will fund your life. The good news is that the system is legible once you understand it."},
  {"type":"section","heading":"The UK Has No Special Arrangement for Americans","text":"This surprises a lot of people. There is no special American visa for the UK, no bilateral arrangement that gives US citizens an easier path to long-term residence than any other non-UK national. Since the UK points-based immigration system launched in 2021, Americans are treated the same as everyone else from outside the UK. What Americans have going for them: automatic English language exemption, no tuberculosis test requirement, and smartphone-based biometric enrollment."},
  {"type":"section","heading":"Choosing Your Route: What Are You Moving For?","list":["Moving for work: Skilled Worker visa requires a job offer from a licensed sponsor and minimum salary of £41,700 per year","Ages 18-30 moving for work: Youth Mobility Scheme offers 2 years with any employer, no salary threshold or sponsorship needed","For recognized leaders: Global Talent visa requires no job offer — endorsement from a designated body in your field","For entrepreneurs: Innovator Founder visa requires an endorsed innovative business plan","Moving for family: UK Family Visa requires your UK partner to earn at least £29,000 per year","Moving to study: UK Student Visa requires an unconditional offer from a licensed UK institution"]},
  {"type":"section","heading":"Real Costs of Moving to the UK","list":["Skilled Worker visa (3 years): £769 application fee + £3,105 Immigration Health Surcharge = approx. £3,874 upfront","Family visa (2.5 years): £1,258 application fee + approx. £2,587 IHS = approx. £3,845 upfront","Student visa: £490 application fee + discounted IHS (£776/year for students)","ILR after 5 years: £3,029 application fee","British citizenship after ILR: £1,605 naturalisation fee"]},
  {"type":"section","heading":"The Path to Indefinite Leave to Remain (ILR)","text":"ILR is the UK equivalent of a US Green Card — permanent residence with the right to live and work in the UK without immigration restrictions. The standard route requires 5 years of continuous lawful residence, no more than 180 days outside the UK in any 12-month period, passing the Life in the UK test, and paying £3,029. After 12 months on ILR, you can apply for British citizenship. The UK does not require you to renounce your US citizenship — most Americans who naturalise become dual British-American citizens."},
  {"type":"callout","calloutType":"tip","text":"Dual citizenship advantage: Once you hold a British passport, you never need a UK ETA, visa, or pre-travel permission again. You can also travel visa-free to EU countries for up to 90 days per visit (subject to the Schengen 90/180-day rule)."},
  {"type":"section","heading":"Common Mistakes Americans Make When Moving to the UK","list":["Treating the ETA as a relocation tool — using repeated tourist visits to effectively live in the UK without a visa","Underestimating the Immigration Health Surcharge — must be paid upfront and cannot be refunded if plans change","Choosing the wrong visa route — some routes do not count toward the ILR clock for certain settlement pathways","Exceeding the 180-day overseas absence limit — even one trip that pushes you over can jeopardize ILR eligibility","Forgetting to create a UKVI account — your immigration status is now held digitally and must be shared with employers and landlords"]},
  {"type":"faq","items":[{"q":"Can I move to the UK without a job offer?","a":"Yes, on certain routes. The Youth Mobility Scheme (ages 18-30), Global Talent visa, Innovator Founder visa, and Family visa all allow entry without a pre-arranged UK job offer. The Skilled Worker visa does require a job offer from a licensed UK sponsor."},{"q":"How long does it take to move to the UK?","a":"Once you have a job offer and Certificate of Sponsorship, a Skilled Worker visa typically takes 3-8 weeks to process from outside the UK. Adding the job search and offer stage, most Americans report a total timeline of 3-12 months from deciding to move to landing in the UK."},{"q":"Do I need to give up my US citizenship to become British?","a":"No. The UK does not require you to renounce your US citizenship to naturalise as British. The vast majority of Americans who go through the UK citizenship process become dual British-American citizens."},{"q":"Can I access the NHS immediately on arrival?","a":"Yes — if you paid the Immigration Health Surcharge as part of your visa application, you have full NHS access from the day you arrive. Register with a local GP as soon as you are settled."}]}
]'::jsonb
WHERE slug = 'moving-to-uk-from-usa';
