/*
  # Add Israel Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Israeli passport holders traveling to all 51 active destinations.

  ## Israel Passport Profile
  - Strong passport with ~160 visa-free destinations
  - NOT EU/Schengen member - subject to 90/180 Schengen rule
  - Strong bilateral agreements with US, EU, and many western countries
  - Notable restrictions: Arab League countries generally restrict entry (varies)
  - Key caveat: Some countries deny entry to passport holders with Israeli stamps

  ## Important Notes
  - Several Arab/Muslim-majority countries: entry denied or heavily restricted
  - Travelers should be aware of stamp issues (can request no stamp)
  - Regional conflict may affect advisories

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
-- Schengen/EU countries - visa-free 90 days (not unlimited - Israel not EU)
(gen_random_uuid(), 'israel', 'austria', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.bmeia.gv.at', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Austria. Subject to 90/180 Schengen rule across all Schengen countries combined.'),
(gen_random_uuid(), 'israel', 'belgium', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://dofi.ibz.be', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Belgium. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'croatia', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://mup.gov.hr', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Croatia. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'czech-republic', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mvcr.cz', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Czech Republic. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Denmark. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Finland. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'france', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://france-visas.gouv.fr', '2026-02-24', 'Israeli passport holders enjoy visa-free access to France. Subject to 90/180 Schengen rule. Large Jewish community in France.'),
(gen_random_uuid(), 'israel', 'germany', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.bmi.bund.de', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Germany. Subject to 90/180 Schengen rule. Strong bilateral relations.'),
(gen_random_uuid(), 'israel', 'greece', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.ypes.gr', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Greece. Subject to 90/180 Schengen rule. Popular destination for Israeli tourists.'),
(gen_random_uuid(), 'israel', 'hungary', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.kormany.hu', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Hungary. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'italy', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.interno.gov.it', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Italy. Subject to 90/180 Schengen rule. Popular tourist destination.'),
(gen_random_uuid(), 'israel', 'netherlands', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://ind.nl', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Netherlands. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Norway. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'poland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Poland. Subject to 90/180 Schengen rule. Historic Jewish heritage.'),
(gen_random_uuid(), 'israel', 'portugal', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.sef.pt', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Portugal. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'spain', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.interior.gob.es', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Spain. Subject to 90/180 Schengen rule. Popular tourist destination.'),
(gen_random_uuid(), 'israel', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Sweden. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'israel', 'switzerland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.sem.admin.ch', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Switzerland. Subject to 90/180 Schengen rule.'),
-- EU non-Schengen
(gen_random_uuid(), 'israel', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. Ireland not in Schengen so separate 90-day allowance.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Ireland. Separate from Schengen quota.'),
(gen_random_uuid(), 'israel', 'romania', 'visa_free', NULL, 90, 180, '90 days within any 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Romania. Romania joined Schengen in 2024 - Schengen rules apply.'),
-- UK - visa-free
(gen_random_uuid(), 'israel', 'united-kingdom', 'visa_free', NULL, 180, NULL, 'Up to 6 months per visit for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.uk/visit-uk', '2026-02-24', 'Israeli passport holders enjoy visa-free access to UK. Standard visitor visa rules apply. Cannot work or study without permission.'),
-- Americas
(gen_random_uuid(), 'israel', 'argentina', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Argentina.'),
(gen_random_uuid(), 'israel', 'brazil', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Brazil.'),
(gen_random_uuid(), 'israel', 'chile', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Chile.'),
(gen_random_uuid(), 'israel', 'colombia', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Colombia.'),
(gen_random_uuid(), 'israel', 'mexico', 'visa_free', NULL, 180, NULL, 'Up to 180 days. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Mexico.'),
(gen_random_uuid(), 'israel', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Peru.'),
-- ETAs/eVisas
(gen_random_uuid(), 'israel', 'australia', 'evisa', 'ETA', 90, NULL, '90 days per visit within 12-month validity. Multiple entries permitted.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601', '2026-02-24', 'Israeli passport holders eligible for ETA (subclass 601), AUD $20 fee. Apply online before travel.'),
(gen_random_uuid(), 'israel', 'canada', 'evisa', 'eTA', 180, NULL, 'Up to 6 months per entry.', NULL, 'valid_for_stay', 'may_be_requested', 'required', 'may_be_requested', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html', '2026-02-24', 'eTA required for Israeli citizens arriving by air. CAD $7 fee, valid 5 years.'),
(gen_random_uuid(), 'israel', 'new-zealand', 'evisa', 'NZeTA', 90, NULL, '90 days per visit within 18-month validity.', 3, '3_months_beyond_departure', 'required', 'required', 'may_be_requested', 'https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/nzeta', '2026-02-24', 'NZeTA required before travel. NZD $17 via app. IVL of NZD $35 also required.'),
(gen_random_uuid(), 'israel', 'united-states', 'evisa', 'ESTA', 90, NULL, '90 days for tourism/business under Visa Waiver Program.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://esta.cbp.dhs.gov', '2026-02-24', 'ESTA required under Visa Waiver Program. USD $21 fee, valid 2 years. Strong US-Israel relations.'),
(gen_random_uuid(), 'israel', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days. eBusiness: up to 180 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Israeli passport holders must obtain eVisa before travel. Apply at least 4 days before.'),
(gen_random_uuid(), 'israel', 'nigeria', 'evisa', 'eVisa on Arrival', 90, NULL, '90 days tourist/business visa.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://portal.immigration.gov.ng', '2026-02-24', 'Israeli passport holders must obtain eVisa before travel. USD $160 fee. Yellow fever certificate mandatory.'),
-- Visa on Arrival
(gen_random_uuid(), 'israel', 'egypt', 'visa_on_arrival', 'VOA or eVisa', 30, NULL, '30 days. Note: Israel-Egypt relations may affect entry points.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Israeli passport holders can enter Egypt via Sinai (free, 14 days), Taba crossing or Cairo airport. Peace treaty between Israel and Egypt since 1979. Full visa available at airports.'),
(gen_random_uuid(), 'israel', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available. Note: Some areas may have restrictions. Check current advisories.'),
(gen_random_uuid(), 'israel', 'thailand', 'visa_free', NULL, 60, NULL, '60 days visa exemption. Extendable once for 30 days.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Israeli passport holders enjoy 60-day visa-free entry.'),
(gen_random_uuid(), 'israel', 'japan', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Japan under bilateral agreement.'),
(gen_random_uuid(), 'israel', 'south-korea', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.k-eta.go.kr', '2026-02-24', 'Israeli passport holders enjoy visa-free access. K-ETA recommended for smoother entry.'),
(gen_random_uuid(), 'israel', 'singapore', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Israeli passport holders enjoy visa-free access to Singapore.'),
(gen_random_uuid(), 'israel', 'malaysia', 'visa_required', NULL, NULL, NULL, 'Entry not permitted. Malaysia does not recognize Israel and denies entry to Israeli passport holders.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Malaysian law prohibits Israeli passport holders from entering. This is a longstanding policy. Travelers should be aware and plan accordingly.'),
(gen_random_uuid(), 'israel', 'south-africa', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'Israeli passport holders enjoy visa-free access to South Africa.'),
(gen_random_uuid(), 'israel', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable through Bureau of Immigration.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Israeli passport holders receive 30-day visa-free entry. Extensions available.'),
(gen_random_uuid(), 'israel', 'vietnam', 'evisa', 'eVisa', 90, NULL, '90 days single or multiple entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Israeli passport holders can obtain eVisa (USD $25) valid for 90 days.'),
(gen_random_uuid(), 'israel', 'china', 'visa_free', NULL, 15, NULL, 'Visa-free up to 15 days for tourism/transit under China-Israel bilateral agreement (2023).', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China signed visa-free agreement with Israel in 2023. Israeli passport holders can visit China for up to 15 days without a visa.'),
-- Restricted destinations
(gen_random_uuid(), 'israel', 'qatar', 'visa_free', NULL, 90, NULL, '90 days visa-free under normalization/bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Qatar opened to Israeli passport holders. Abraham Accords context. Check current status as situation may change.'),
(gen_random_uuid(), 'israel', 'united-arab-emirates', 'visa_free', NULL, 90, NULL, '90 days visa-free under Abraham Accords normalization.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'UAE normalized relations with Israel via Abraham Accords (2020). Israeli passport holders enjoy visa-free access. Direct flights available.'),
(gen_random_uuid(), 'israel', 'morocco', 'visa_free', NULL, 90, NULL, '90 days visa-free under Abraham Accords normalization.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Morocco normalized relations with Israel via Abraham Accords (2020). Israeli passport holders enjoy visa-free access. Large Moroccan-Jewish heritage connection.'),
(gen_random_uuid(), 'israel', 'russia', 'visa_free', NULL, 90, 180, '90 days per 180-day period under bilateral visa-free agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://electronic-visa.kdmid.ru', '2026-02-24', 'Israel and Russia have bilateral visa-free agreement. Travel advisory in place. Large Russian-speaking Jewish community in Israel.'),
(gen_random_uuid(), 'israel', 'saudi-arabia', 'visa_required', NULL, NULL, NULL, 'Visa required. Saudi Arabia has limited entry for Israeli passport holders. Situation evolving with normalization talks.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.neom.com', '2026-02-24', 'Saudi Arabia does not have full diplomatic relations with Israel as of 2026. Entry is very limited. Normalization talks ongoing. Check current status before travel.'),
(gen_random_uuid(), 'israel', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Israeli passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Check Israeli government advisories before travel.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
