/*
  # Add Peru Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Peruvian passport holders traveling to all 51 active destinations.

  ## Peru Passport Profile
  - Mid-tier Latin American passport with ~130 visa-free destinations
  - Strong visa-free access within Latin America
  - Limited access to US, Canada, Australia - requires visas
  - Decent access to Europe (Schengen) - 90 days visa-free
  - Good access to Southeast Asia

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
-- Schengen - visa-free 90/180
(gen_random_uuid(), 'peru', 'austria', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Combined across all Schengen countries.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.bmeia.gv.at', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Austria under Schengen visa waiver. Subject to 90/180 rule. Travel insurance and proof of funds required.'),
(gen_random_uuid(), 'peru', 'belgium', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://dofi.ibz.be', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Belgium. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'croatia', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://mup.gov.hr', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Croatia. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'czech-republic', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mvcr.cz', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Czech Republic. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Denmark. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Finland. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'france', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://france-visas.gouv.fr', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to France. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'germany', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.bmi.bund.de', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Germany. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'greece', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.ypes.gr', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Greece. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'hungary', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.kormany.hu', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Hungary. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'italy', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.interno.gov.it', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Italy. Popular European destination. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'netherlands', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://ind.nl', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Netherlands. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.udi.no', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Norway. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'poland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Poland. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'portugal', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.sef.pt', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Portugal. Strong cultural ties. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'spain', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.interior.gob.es', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Spain. Strong cultural and historical ties. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Sweden. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'peru', 'switzerland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.sem.admin.ch', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Switzerland. Subject to 90/180 Schengen rule.'),
-- EU non-Schengen
(gen_random_uuid(), 'peru', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. Separate from Schengen.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Ireland. Separate from Schengen quota.'),
(gen_random_uuid(), 'peru', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day period. Romania is Schengen member.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Romania.'),
-- Latin America - generally visa-free
(gen_random_uuid(), 'peru', 'argentina', 'visa_free', NULL, 90, NULL, '90 days per entry. Extendable under Mercosur agreements.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Argentina under CAN/Mercosur agreements.'),
(gen_random_uuid(), 'peru', 'brazil', 'visa_free', NULL, 90, 180, '90 days per 180-day period under Mercosur agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Brazil under South American integration agreements.'),
(gen_random_uuid(), 'peru', 'chile', 'visa_free', NULL, 90, NULL, '90 days per entry under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Chile. Strong bilateral ties.'),
(gen_random_uuid(), 'peru', 'colombia', 'visa_free', NULL, 180, NULL, 'Up to 180 days per year under Andean Community (CAN) agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Peruvian passport holders enjoy enhanced visa-free access under Andean Community (CAN). Both countries are CAN members.'),
(gen_random_uuid(), 'peru', 'mexico', 'visa_free', NULL, 180, NULL, 'Up to 180 days. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Mexico.'),
-- UK
(gen_random_uuid(), 'peru', 'united-kingdom', 'visa_required', NULL, NULL, NULL, 'Standard visitor visa required for tourism/business. Apply in advance at UK Visas and Immigration.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://www.gov.uk/standard-visitor-visa', '2026-02-24', 'Peruvian passport holders require a UK Standard Visitor Visa. Apply through UKVI. Biometric appointment required. Processing time 3-4 weeks.'),
-- Visa required major destinations
(gen_random_uuid(), 'peru', 'australia', 'visa_required', NULL, NULL, NULL, 'Visitor visa required (subclass 600). Apply through ImmiAccount online.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600', '2026-02-24', 'Peruvian passport holders require a Visitor visa for Australia. Apply online. Processing times vary. Must demonstrate ties to Peru and ability to fund stay.'),
(gen_random_uuid(), 'peru', 'canada', 'visa_required', NULL, NULL, NULL, 'Temporary Resident Visa (TRV) required. Apply through IRCC online or at VAC.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html', '2026-02-24', 'Peruvian passport holders require a TRV to visit Canada. Biometric enrollment required. Processing times 2-8 weeks. Must show ties to Peru and financial means.'),
(gen_random_uuid(), 'peru', 'united-states', 'visa_required', NULL, NULL, NULL, 'B-1/B-2 tourist/business visa required. Apply at US Embassy Lima.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html', '2026-02-24', 'Peruvian passport holders require a B-1/B-2 visitor visa. Apply at US Embassy in Lima. Wait times can be several months. Must demonstrate strong ties to Peru.'),
(gen_random_uuid(), 'peru', 'new-zealand', 'visa_required', NULL, NULL, NULL, 'Visitor visa required. Apply through Immigration New Zealand.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.immigration.govt.nz', '2026-02-24', 'Peruvian passport holders require a visitor visa for New Zealand. Apply online through INZ. Processing typically 3-4 weeks.'),
-- Asia
(gen_random_uuid(), 'peru', 'china', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply through Chinese Visa Application Service Center.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China requires visa for Peruvian passport holders. Apply at the Chinese Visa Application Service Center.'),
(gen_random_uuid(), 'peru', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Peruvian passport holders can obtain Indian eVisa. Apply at least 4 days before travel.'),
(gen_random_uuid(), 'peru', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available at major airports. Single entry, tourist only.'),
(gen_random_uuid(), 'peru', 'israel', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Israel. Security screening at entry.'),
(gen_random_uuid(), 'peru', 'japan', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Japan under bilateral agreement. Cannot work or study.'),
(gen_random_uuid(), 'peru', 'malaysia', 'visa_free', NULL, 30, NULL, '30 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Malaysia for up to 30 days.'),
(gen_random_uuid(), 'peru', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable through Bureau of Immigration.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Peruvian passport holders receive 30-day visa-free entry.'),
(gen_random_uuid(), 'peru', 'singapore', 'visa_free', NULL, 30, NULL, '30 days per entry.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Singapore for up to 30 days.'),
(gen_random_uuid(), 'peru', 'south-korea', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.k-eta.go.kr', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to South Korea. K-ETA recommended.'),
(gen_random_uuid(), 'peru', 'thailand', 'visa_free', NULL, 30, NULL, '30 days visa exemption. Extendable once for 30 days.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Peruvian passport holders enjoy visa-free entry to Thailand.'),
(gen_random_uuid(), 'peru', 'vietnam', 'visa_free', NULL, 45, NULL, '45 days visa-free for tourism.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Vietnam for 45 days. eVisa also available for longer stays.'),
-- Middle East / Africa
(gen_random_uuid(), 'peru', 'egypt', 'visa_on_arrival', 'VOA or eVisa', 30, NULL, '30 days single/multiple entry.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Visa on arrival (USD $25) or eVisa online. eVisa recommended.'),
(gen_random_uuid(), 'peru', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'peru', 'nigeria', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Nigerian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://portal.immigration.gov.ng', '2026-02-24', 'Nigerian visa required for Peruvian passport holders. Apply in advance. Yellow fever certificate mandatory.'),
(gen_random_uuid(), 'peru', 'qatar', 'visa_on_arrival', NULL, 30, NULL, '30 days on arrival. Free visa on arrival for tourism.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Peruvian passport holders can obtain visa on arrival in Qatar. Free for tourism.'),
(gen_random_uuid(), 'peru', 'russia', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Russian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://electronic-visa.kdmid.ru', '2026-02-24', 'Russian visa required for Peruvian passport holders. Travel advisory in place due to geopolitical situation.'),
(gen_random_uuid(), 'peru', 'saudi-arabia', 'evisa', 'eVisa', 90, 180, '90 days per visit, up to 180 days per year.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visa.visitsaudi.com', '2026-02-24', 'Tourist eVisa available for Peruvian passport holders. SAR 300 + insurance fee.'),
(gen_random_uuid(), 'peru', 'south-africa', 'visa_free', NULL, 30, NULL, '30 days per entry.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to South Africa for up to 30 days.'),
(gen_random_uuid(), 'peru', 'ukraine', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Peruvian passport holders enjoy visa-free access to Ukraine. IMPORTANT: Active armed conflict. Check official advisories.'),
(gen_random_uuid(), 'peru', 'united-arab-emirates', 'visa_on_arrival', NULL, 30, NULL, '30 days on arrival. Free visa on arrival for tourism.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'Peruvian passport holders can obtain free visa on arrival in UAE for up to 30 days.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
