import type { TransitRule, NationalityGroup } from './types';

export const EU_EEA_SLUGS: string[] = [
  'austria', 'belgium', 'croatia', 'czech-republic', 'denmark', 'finland',
  'france', 'germany', 'greece', 'hungary', 'ireland', 'italy', 'netherlands',
  'norway', 'poland', 'portugal', 'romania', 'spain', 'sweden', 'switzerland',
  'iceland', 'liechtenstein', 'luxembourg', 'slovakia', 'slovenia', 'estonia',
  'latvia', 'lithuania', 'malta', 'bulgaria', 'cyprus',
];

export const FIVE_EYES_SLUGS: string[] = [
  'united-states', 'united-kingdom', 'canada', 'australia', 'new-zealand',
];

export const GCC_SLUGS: string[] = [
  'saudi-arabia', 'united-arab-emirates', 'qatar', 'kuwait', 'bahrain', 'oman',
];

export function isNationalityGroup(slug: string, group: NationalityGroup): boolean {
  switch (group) {
    case 'eu_eea': return EU_EEA_SLUGS.includes(slug);
    case 'five_eyes': return FIVE_EYES_SLUGS.includes(slug);
    case 'gulf_gcc': return GCC_SLUGS.includes(slug);
    case 'schengen_non_eu': return ['norway', 'switzerland', 'iceland', 'liechtenstein'].includes(slug);
    case 'any': return true;
  }
}

export const TRANSIT_RULES: TransitRule[] = [

  // ─── UNITED KINGDOM ────────────────────────────────────────────────────────

  {
    transit_country_slug: 'united-kingdom',
    airport_codes: ['LHR', 'LGW', 'MAN', 'STN', 'LTN', 'BHX', 'EDI', 'GLA'],
    nationality_groups: ['eu_eea', 'five_eyes'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'EU/EEA and Five Eyes nationals do not need a transit visa in the UK under any airside scenario.',
    source: 'UK Home Office – Direct Airside Transit Visa (DATV) guidance',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'united-kingdom',
    airport_codes: ['LHR', 'LGW', 'MAN', 'STN', 'LTN', 'BHX', 'EDI', 'GLA'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'sri-lanka', 'nepal'],
    airside_transit_visa_required: true,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: true,
    exemptions_apply: true,
    exemption_qualifying_visas: ['US visa (valid or expired within 6 months)', 'UK visa (valid)', 'Irish visa (valid)', 'Schengen visa (valid)'],
    exemption_qualifying_permits: ['US Green Card', 'UK BRP', 'EU/EEA residence permit'],
    notes: 'Indian, Pakistani, Bangladeshi, Nigerian, Ghanaian, Sri Lankan, and Nepali passport holders require a Direct Airside Transit Visa (DATV) for all UK airports. Exemptions apply if holding a valid US visa, valid UK visa, valid Irish visa, or valid Schengen visa. A US visa expired within 6 months of travel also qualifies. Self-transfer and terminal changes bring the traveler into immigration scope.',
    source: 'UK Home Office – DATV nationality list; IATA Timatic reference',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'united-kingdom',
    airport_codes: ['LHR', 'LGW', 'MAN', 'STN', 'LTN', 'BHX', 'EDI', 'GLA'],
    passport_slugs: ['china', 'iran', 'iraq', 'afghanistan', 'somalia', 'eritrea', 'ethiopia', 'sudan'],
    airside_transit_visa_required: true,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: true,
    exemptions_apply: true,
    exemption_qualifying_visas: ['US visa (valid)', 'UK visa (valid)', 'Irish visa (valid)', 'Schengen visa (valid)'],
    exemption_qualifying_permits: ['US Green Card', 'UK BRP', 'EU/EEA residence permit'],
    notes: 'Chinese and several high-restriction passports require a DATV for all UK transit. Exemptions exist for valid US, UK, Irish, or Schengen visas.',
    source: 'UK Home Office – DATV nationality list',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'united-kingdom',
    airport_codes: ['LHR', 'LGW', 'MAN', 'STN', 'LTN', 'BHX', 'EDI', 'GLA'],
    passport_slugs: ['south-africa', 'kenya', 'colombia', 'venezuela', 'mexico', 'egypt', 'morocco', 'indonesia', 'philippines', 'vietnam', 'ukraine'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'These nationalities do not require an airside transit visa (DATV) so can connect airside freely. However, self-transfer or terminal change requires clearing UK immigration, which means a full UK visa or ETA is needed.',
    source: 'UK Home Office – DATV exemptions list; UK ETA information',
    last_verified: '2026-02',
    confidence: 'Medium',
  },

  // ─── SCHENGEN (GERMANY as representative, logic applies broadly) ───────────

  {
    transit_country_slug: 'germany',
    airport_codes: ['FRA', 'MUC', 'DUS', 'BER', 'HAM', 'CGN'],
    nationality_groups: ['eu_eea', 'five_eyes'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'EU/EEA and Five Eyes nationals can transit freely through German airports without a transit visa under all scenarios.',
    source: 'German Federal Foreign Office; Schengen Borders Code',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'germany',
    airport_codes: ['FRA', 'MUC', 'DUS', 'BER', 'HAM', 'CGN'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'ethiopia', 'sri-lanka', 'nepal', 'iran', 'iraq', 'afghanistan', 'somalia', 'eritrea', 'sudan'],
    airside_transit_visa_required: true,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: true,
    exemptions_apply: true,
    exemption_qualifying_visas: ['valid Schengen visa', 'valid US visa', 'valid Canadian visa', 'valid UK visa', 'valid Japanese visa'],
    exemption_qualifying_permits: ['US Green Card', 'EU/EEA residence permit', 'Schengen residence permit'],
    notes: 'Airport Transit Visa (ATV) required for these nationalities at all Schengen airports. Exemptions include valid Schengen, US, Canadian, UK, or Japanese visas. Self-transfer or leaving the airport requires a full Schengen visa. The ATV requirement applies uniformly across Schengen members including France, Netherlands, Belgium, and Austria.',
    source: 'EU Visa Code – Airport Transit Visa (ATV); German Federal Foreign Office',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'germany',
    airport_codes: ['FRA', 'MUC', 'DUS', 'BER', 'HAM', 'CGN'],
    passport_slugs: ['china'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'Chinese passport holders do not need an Airport Transit Visa (ATV) for airside transit in Germany. However, any self-transfer, terminal change, or leaving the airport requires a Schengen visa. China was removed from the German ATV list in 2024.',
    source: 'German Federal Foreign Office – ATV exemptions; IATA Timatic',
    last_verified: '2026-02',
    confidence: 'High',
  },

  {
    transit_country_slug: 'france',
    airport_codes: ['CDG', 'ORY'],
    nationality_groups: ['eu_eea', 'five_eyes'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'EU/EEA and Five Eyes nationals transit freely through French airports.',
    source: 'French Ministry of Foreign Affairs; EU Visa Code',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'france',
    airport_codes: ['CDG', 'ORY'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'ethiopia', 'sri-lanka', 'iran', 'iraq', 'afghanistan'],
    airside_transit_visa_required: true,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: true,
    exemptions_apply: true,
    exemption_qualifying_visas: ['valid Schengen visa', 'valid US visa', 'valid Canadian visa', 'valid UK visa', 'valid Japanese visa'],
    exemption_qualifying_permits: ['US Green Card', 'EU/EEA residence permit'],
    notes: 'France applies the EU Airport Transit Visa (ATV) requirement. Same logic as Germany for Schengen ATV countries.',
    source: 'French Ministry of Foreign Affairs – ATV list; EU Visa Code',
    last_verified: '2026-02',
    confidence: 'High',
  },

  {
    transit_country_slug: 'netherlands',
    airport_codes: ['AMS'],
    nationality_groups: ['eu_eea', 'five_eyes'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'EU/EEA and Five Eyes nationals transit freely through Amsterdam Schiphol.',
    source: 'Dutch Immigration and Naturalisation Service (IND); EU Visa Code',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'netherlands',
    airport_codes: ['AMS'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'ethiopia', 'sri-lanka', 'iran', 'iraq', 'afghanistan'],
    airside_transit_visa_required: true,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: true,
    exemptions_apply: true,
    exemption_qualifying_visas: ['valid Schengen visa', 'valid US visa', 'valid Canadian visa', 'valid UK visa'],
    exemption_qualifying_permits: ['US Green Card', 'EU/EEA residence permit'],
    notes: 'Schiphol applies the EU ATV requirement for the same nationalities as Germany and France.',
    source: 'Dutch IND – ATV list; EU Visa Code',
    last_verified: '2026-02',
    confidence: 'High',
  },

  // ─── UNITED ARAB EMIRATES ──────────────────────────────────────────────────

  {
    transit_country_slug: 'united-arab-emirates',
    airport_codes: ['DXB', 'AUH', 'SHJ'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'The UAE allows airside transit without a visa for all nationalities. Passengers do not need a transit visa to connect airside at DXB, AUH, or SHJ. Leaving the airport requires a UAE visa or visa on arrival (available to most Western passport holders). Self-transfer at DXB within the same terminal group (T1/T2/T3) generally does not require clearing immigration if on Emirates or within the sterile zone.',
    source: 'UAE General Directorate of Residency and Foreigners Affairs; Emirates airline DATV guidance',
    last_verified: '2026-02',
    confidence: 'High',
  },

  // ─── SINGAPORE ─────────────────────────────────────────────────────────────

  {
    transit_country_slug: 'singapore',
    airport_codes: ['SIN'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'Singapore does not require a transit visa for airside connections. Changi Airport (SIN) allows free movement between terminals without clearing immigration, making it a strong transit hub. Self-transfer (separate tickets) where the traveler must re-check bags may require clearing immigration and obtaining entry to Singapore. Most nationalities can enter Singapore visa-free for up to 30–90 days. Indian, Pakistani, and some other passport holders may require an IPA (In-Principle Approval) or have restricted entry without a visit pass.',
    source: 'Singapore ICA – Visa and pass requirements; Changi Airport transit information',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'singapore',
    airport_codes: ['SIN'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'sri-lanka', 'egypt', 'iraq', 'iran', 'afghanistan'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'For these nationalities, airside transit at SIN is visa-free. However, self-transfer or leaving the airport requires a Singapore visa or visit pass. Indian passport holders on the Singapore Visa (STVP) can enter; Indian CECA professionals may transit under specific arrangements.',
    source: 'Singapore ICA – Nationalities requiring visas; Changi Airport',
    last_verified: '2026-02',
    confidence: 'Medium',
  },

  // ─── JAPAN ─────────────────────────────────────────────────────────────────

  {
    transit_country_slug: 'japan',
    airport_codes: ['NRT', 'HND', 'KIX', 'NGO'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'Japan does not require a transit visa for short airside connections at NRT, HND, or other major airports for most nationalities. Japan also offers a Shore Pass (shoreside transit) allowing passengers to leave the airport for up to 72 hours without a visa under certain conditions. Self-transfer (booking a separate ticket) requires entering Japan, which is visa-free for most Western passports but requires a visa for Indian, Pakistani, and other controlled nationalities.',
    source: 'Japan Ministry of Foreign Affairs – Visa exemption arrangements; JNTO transit guide',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'japan',
    airport_codes: ['NRT', 'HND', 'KIX', 'NGO'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'indonesia', 'vietnam', 'philippines', 'iran', 'iraq', 'afghanistan', 'nigeria', 'ghana', 'nepal', 'sri-lanka', 'egypt', 'morocco'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'These nationalities can transit airside without a visa in Japan. However, entering Japan (including self-transfer, terminal recheck, or leaving the airport) requires a Japanese visa. Japan does not have an ATV system — airside is always allowed, but entry is the gating factor.',
    source: 'Japan MOJ – Countries requiring visas; Japan Airlines and ANA transit policies',
    last_verified: '2026-02',
    confidence: 'High',
  },

  // ─── SOUTH KOREA ───────────────────────────────────────────────────────────

  {
    transit_country_slug: 'south-korea',
    airport_codes: ['ICN', 'GMP'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'South Korea allows airside transit without a visa at ICN for most nationalities. Korea also offers a Transit Without Visa (TWOV) scheme: passengers transiting to a third country can often leave the airport for up to 24 hours without a visa. Incheon Airport is a major hub with efficient connections. Self-transfer requires entering Korea.',
    source: 'Korea Immigration Service – TWOV; Korea Tourism Organization',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'south-korea',
    airport_codes: ['ICN', 'GMP'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'iran', 'iraq', 'afghanistan', 'nepal', 'sri-lanka'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'For controlled nationalities, airside transit at ICN is visa-free. TWOV (leave airport) may still be available on a case-by-case basis per Korea Immigration discretion. Self-transfer requires a Korean visa for these passport holders.',
    source: 'Korea Immigration Service – Visa required nationals; IATA Timatic',
    last_verified: '2026-02',
    confidence: 'Medium',
  },

  // ─── QATAR ─────────────────────────────────────────────────────────────────

  {
    transit_country_slug: 'qatar',
    airport_codes: ['DOH'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'Qatar generally does not require a transit visa for airside connections at Hamad International Airport (DOH). Qatar Airways passengers also benefit from a complimentary stopover or transit visa policy. Most nationalities can also enter Qatar visa-free or with a visa on arrival for up to 30 days, making landside transit accessible for most travelers.',
    source: 'Qatar Ministry of Interior – Visa information; Qatar Airways transit visa policy',
    last_verified: '2026-02',
    confidence: 'High',
  },

  // ─── TURKEY ────────────────────────────────────────────────────────────────

  {
    transit_country_slug: 'turkey',
    airport_codes: ['IST', 'SAW', 'AYT'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'Turkey does not require a transit visa for airside connections at IST or SAW for most nationalities. Istanbul Airport (IST) is a major hub with excellent connections. Many nationalities can obtain a Turkish e-Visa for under $100 if they wish to leave the airport. Citizens of certain countries (Iran, Nigeria, Pakistan, Afghanistan, Somalia, Iraq, Yemen, Syria) are restricted and may face additional requirements for entry — but airside transit is generally still permitted without a visa.',
    source: 'Turkish Ministry of Foreign Affairs – Visa information; Istanbul Airport transit guide',
    last_verified: '2026-02',
    confidence: 'High',
  },

  // ─── SAUDI ARABIA ──────────────────────────────────────────────────────────

  {
    transit_country_slug: 'saudi-arabia',
    airport_codes: ['RUH', 'JED', 'DMM'],
    nationality_groups: ['eu_eea', 'five_eyes', 'gulf_gcc'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'EU/EEA, Five Eyes, and GCC nationals can transit through Saudi airports without a transit visa. Saudi Arabia also now issues transit visas for layovers exceeding the airside transit window.',
    source: 'Saudi Ministry of Interior – Iqama and visa; Saudi tourism authority',
    last_verified: '2026-02',
    confidence: 'Medium',
  },
  {
    transit_country_slug: 'saudi-arabia',
    airport_codes: ['RUH', 'JED', 'DMM'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'indonesia', 'philippines', 'nepal', 'sri-lanka', 'iran', 'iraq', 'egypt', 'morocco'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'For these nationalities at Saudi airports, airside transit is permitted without a visa. However, leaving the airport or any scenario requiring immigration clearance (self-transfer, terminal change) requires a Saudi visa. Saudi Arabia does not maintain a formal ATV system.',
    source: 'Saudi MOI – Visa nationals list; IATA Timatic',
    last_verified: '2026-02',
    confidence: 'Medium',
  },

  // ─── CHINA ─────────────────────────────────────────────────────────────────

  {
    transit_country_slug: 'china',
    airport_codes: ['PEK', 'PVG', 'CAN', 'CTU', 'HGH'],
    nationality_groups: ['any'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'China offers a 24-hour/144-hour/240-hour visa-free transit policy at many major airports for nationals of qualifying countries (currently 54 countries as of 2026, including most Western passport holders). Qualifying travelers can leave the airport without a visa for up to 144 hours at Beijing (PEK/PKX), Shanghai (PVG/SHA), Guangzhou (CAN), Chengdu (CTU), Hangzhou (HGH), and other designated airports. Non-qualifying nationalities and self-transfers at airports not covered may require a Chinese visa.',
    source: 'China National Immigration Administration – 144-hour visa-free transit; CAAC',
    last_verified: '2026-02',
    confidence: 'Medium',
  },
  {
    transit_country_slug: 'china',
    airport_codes: ['PEK', 'PVG', 'CAN', 'CTU', 'HGH'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'nepal', 'sri-lanka', 'iraq', 'iran', 'afghanistan', 'somalia', 'eritrea'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'These nationalities are not included in China\'s 144-hour visa-free transit policy. Airside transit within the international departure area is generally permitted without a visa. However, leaving the airport or any scenario requiring immigration clearance requires a Chinese visa.',
    source: 'China NIA – Visa exempt nationals list; Beijing Capital Airport transit guide',
    last_verified: '2026-02',
    confidence: 'Medium',
  },

  // ─── CANADA ────────────────────────────────────────────────────────────────

  {
    transit_country_slug: 'canada',
    airport_codes: ['YYZ', 'YVR', 'YUL', 'YYC', 'YEG'],
    nationality_groups: ['eu_eea', 'five_eyes'],
    airside_transit_visa_required: false,
    landside_entry_requires_visa: false,
    terminal_change_triggers_immigration: false,
    self_transfer_triggers_immigration: false,
    leaving_airport_requires_visa: false,
    transit_visa_required: false,
    exemptions_apply: false,
    exemption_qualifying_visas: [],
    exemption_qualifying_permits: [],
    notes: 'EU/EEA and Five Eyes nationals do not need a transit visa in Canada. Note that most EU nationals require an eTA (Electronic Travel Authorization) to transit through Canadian airports — eTA is distinct from a transit visa and can be obtained online in advance.',
    source: 'Immigration, Refugees and Citizenship Canada (IRCC) – Transit visa; eTA requirements',
    last_verified: '2026-02',
    confidence: 'High',
  },
  {
    transit_country_slug: 'canada',
    airport_codes: ['YYZ', 'YVR', 'YUL', 'YYC', 'YEG'],
    passport_slugs: ['india', 'pakistan', 'bangladesh', 'nigeria', 'ghana', 'sri-lanka', 'nepal', 'indonesia', 'philippines', 'vietnam', 'iran', 'iraq', 'afghanistan', 'china', 'egypt', 'morocco', 'colombia', 'mexico'],
    airside_transit_visa_required: true,
    landside_entry_requires_visa: true,
    terminal_change_triggers_immigration: true,
    self_transfer_triggers_immigration: true,
    leaving_airport_requires_visa: true,
    transit_visa_required: true,
    exemptions_apply: true,
    exemption_qualifying_visas: ['valid US visa (B-1/B-2)', 'valid Canadian visa'],
    exemption_qualifying_permits: ['US Green Card', 'Canadian PR card'],
    notes: 'Canada requires a Transit Visa (C1) for these nationalities for all connections, including airside. Exemptions apply for holders of a valid US B-1/B-2 visa or US Green Card. Self-transfer always triggers immigration and requires a full visitor visa.',
    source: 'IRCC – Transit visa requirements; CIC transit exemptions guide',
    last_verified: '2026-02',
    confidence: 'High',
  },
];

export const TRANSIT_AIRPORTS: { code: string; name: string; country_slug: string }[] = [
  { code: 'LHR', name: 'London Heathrow (LHR)', country_slug: 'united-kingdom' },
  { code: 'LGW', name: 'London Gatwick (LGW)', country_slug: 'united-kingdom' },
  { code: 'MAN', name: 'Manchester (MAN)', country_slug: 'united-kingdom' },
  { code: 'STN', name: 'London Stansted (STN)', country_slug: 'united-kingdom' },
  { code: 'FRA', name: 'Frankfurt (FRA)', country_slug: 'germany' },
  { code: 'MUC', name: 'Munich (MUC)', country_slug: 'germany' },
  { code: 'BER', name: 'Berlin Brandenburg (BER)', country_slug: 'germany' },
  { code: 'CDG', name: 'Paris Charles de Gaulle (CDG)', country_slug: 'france' },
  { code: 'ORY', name: 'Paris Orly (ORY)', country_slug: 'france' },
  { code: 'AMS', name: 'Amsterdam Schiphol (AMS)', country_slug: 'netherlands' },
  { code: 'DXB', name: 'Dubai International (DXB)', country_slug: 'united-arab-emirates' },
  { code: 'AUH', name: 'Abu Dhabi (AUH)', country_slug: 'united-arab-emirates' },
  { code: 'SIN', name: 'Singapore Changi (SIN)', country_slug: 'singapore' },
  { code: 'NRT', name: 'Tokyo Narita (NRT)', country_slug: 'japan' },
  { code: 'HND', name: 'Tokyo Haneda (HND)', country_slug: 'japan' },
  { code: 'KIX', name: 'Osaka Kansai (KIX)', country_slug: 'japan' },
  { code: 'ICN', name: 'Seoul Incheon (ICN)', country_slug: 'south-korea' },
  { code: 'DOH', name: 'Doha Hamad (DOH)', country_slug: 'qatar' },
  { code: 'IST', name: 'Istanbul Airport (IST)', country_slug: 'turkey' },
  { code: 'SAW', name: 'Istanbul Sabiha Gökçen (SAW)', country_slug: 'turkey' },
  { code: 'RUH', name: 'Riyadh King Khalid (RUH)', country_slug: 'saudi-arabia' },
  { code: 'JED', name: 'Jeddah King Abdulaziz (JED)', country_slug: 'saudi-arabia' },
  { code: 'PEK', name: 'Beijing Capital (PEK)', country_slug: 'china' },
  { code: 'PVG', name: 'Shanghai Pudong (PVG)', country_slug: 'china' },
  { code: 'CAN', name: 'Guangzhou Baiyun (CAN)', country_slug: 'china' },
  { code: 'YYZ', name: 'Toronto Pearson (YYZ)', country_slug: 'canada' },
  { code: 'YVR', name: 'Vancouver (YVR)', country_slug: 'canada' },
  { code: 'YUL', name: 'Montreal Trudeau (YUL)', country_slug: 'canada' },
];

export function getAirportsForCountry(countrySlug: string) {
  return TRANSIT_AIRPORTS.filter(a => a.country_slug === countrySlug);
}

export function findTransitRules(
  passportSlug: string,
  transitCountrySlug: string,
  airportCode: string,
): TransitRule[] {
  return TRANSIT_RULES.filter(rule => {
    if (rule.transit_country_slug !== transitCountrySlug) return false;
    if (rule.airport_codes.length > 0 && !rule.airport_codes.includes(airportCode)) return false;

    const matchesPassport = rule.passport_slugs?.includes(passportSlug);
    const matchesGroup = rule.nationality_groups?.some(g => isNationalityGroup(passportSlug, g));

    return matchesPassport || matchesGroup;
  });
}
