import type { PassportValidityRule } from './types';

export const PASSPORT_VALIDITY_RULES: PassportValidityRule[] = [
  // -------------------------------------------------------------------------
  // DURATION OF STAY (valid only for the trip itself)
  // -------------------------------------------------------------------------
  {
    destinationSlug: 'united-states',
    destinationName: 'United States',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Your passport must be valid for the entire duration of your stay. No extra months required beyond your departure date.',
    notes: 'US CBP requires passport valid through your departure date. Airlines and CBP verify this at check-in.',
    source: 'US Customs and Border Protection (CBP)',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'united-kingdom',
    destinationName: 'United Kingdom',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Your passport must be valid for the entire intended stay. No 6-month buffer required.',
    notes: 'Post-Brexit UK Border Force rule. Passport must be valid on arrival and throughout the stay.',
    source: 'UK Home Office / GOV.UK',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'australia',
    destinationName: 'Australia',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 2,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must be valid for the full duration of stay in Australia.',
    notes: 'Australian Border Force requirement. eTA holders must also have a valid passport throughout their stay.',
    source: 'Australian Border Force / Department of Home Affairs',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'new-zealand',
    destinationName: 'New Zealand',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must be valid for the entirety of your stay in New Zealand.',
    notes: 'Immigration New Zealand guidance. Passport must not expire during your stay.',
    source: 'Immigration New Zealand',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'canada',
    destinationName: 'Canada',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must be valid for your entire stay in Canada.',
    notes: 'IRCC requirement. Passport must be valid at arrival and throughout the visit.',
    source: 'Immigration, Refugees and Citizenship Canada (IRCC)',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'japan',
    destinationName: 'Japan',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must remain valid for the entire period of stay. No extra buffer required.',
    notes: 'Japan Immigration Bureau rule. Passport must not expire during your stay.',
    source: 'Japan Immigration Bureau',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'south-korea',
    destinationName: 'South Korea',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must be valid for your entire stay in South Korea.',
    notes: 'Korea Immigration Service rule.',
    source: 'Korea Immigration Service',
    lastVerified: '2026-01',
    confidence: 'High',
  },

  // -------------------------------------------------------------------------
  // 3 MONTHS BEYOND DEPARTURE — Schengen Area
  // -------------------------------------------------------------------------
  {
    destinationSlug: 'france',
    destinationName: 'France',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen Borders Code standard. Also note the Schengen 10-year issuance rule: passport must have been issued within the last 10 years.',
    source: 'Schengen Borders Code / EU Regulation 2016/399',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'germany',
    destinationName: 'Germany',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen rule. Passport also must have been issued within the last 10 years.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'italy',
    destinationName: 'Italy',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen Borders Code standard.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'spain',
    destinationName: 'Spain',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen Borders Code standard.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'netherlands',
    destinationName: 'Netherlands',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen Borders Code standard.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'portugal',
    destinationName: 'Portugal',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen Borders Code standard.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'greece',
    destinationName: 'Greece',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    notes: 'Schengen Borders Code standard.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'austria',
    destinationName: 'Austria',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'belgium',
    destinationName: 'Belgium',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'switzerland',
    destinationName: 'Switzerland',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from Schengen. Switzerland is part of the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'denmark',
    destinationName: 'Denmark',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'finland',
    destinationName: 'Finland',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'norway',
    destinationName: 'Norway',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure. Norway is part of the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'sweden',
    destinationName: 'Sweden',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'czech-republic',
    destinationName: 'Czech Republic',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'poland',
    destinationName: 'Poland',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'hungary',
    destinationName: 'Hungary',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure from the Schengen Area.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'croatia',
    destinationName: 'Croatia',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 2,
    ruleLabel: '3 months beyond departure (Schengen)',
    ruleSummary: 'Passport must be valid for at least 3 months after your planned departure. Croatia joined Schengen in January 2023.',
    source: 'Schengen Borders Code',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'ireland',
    destinationName: 'Ireland',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Ireland is not part of the Schengen Area. Passport must be valid for the duration of stay.',
    notes: 'Ireland operates its own immigration controls and is not part of the Schengen Area.',
    source: 'Irish Naturalisation and Immigration Service (INIS)',
    lastVerified: '2026-01',
    confidence: 'High',
  },

  // -------------------------------------------------------------------------
  // 6 MONTHS BEYOND STAY
  // -------------------------------------------------------------------------
  {
    destinationSlug: 'thailand',
    destinationName: 'Thailand',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your intended departure from Thailand.',
    notes: 'Thai Immigration Bureau standard. Most airlines enforce this at check-in.',
    source: 'Thailand Immigration Bureau',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'singapore',
    destinationName: 'Singapore',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your departure from Singapore.',
    notes: 'ICA (Immigration & Checkpoints Authority) standard. Strictly enforced.',
    source: 'Immigration & Checkpoints Authority (ICA), Singapore',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'indonesia',
    destinationName: 'Indonesia',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Indonesia.',
    source: 'Directorate General of Immigration, Indonesia',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'vietnam',
    destinationName: 'Vietnam',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your intended departure from Vietnam.',
    source: 'Vietnam Immigration Department',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'malaysia',
    destinationName: 'Malaysia',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your intended departure from Malaysia.',
    source: 'Malaysia Immigration Department',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'china',
    destinationName: 'China',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from China.',
    notes: 'National Immigration Administration standard. Also requires blank pages for visa stamp.',
    source: 'National Immigration Administration, China',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'india',
    destinationName: 'India',
    ruleType: 'six_months_from_entry',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months from date of arrival',
    ruleSummary: 'Passport must be valid for at least 6 months from your date of arrival in India.',
    notes: 'Bureau of Immigration India. The 6-month clock starts from arrival date, not departure date.',
    source: 'Bureau of Immigration, India',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'united-arab-emirates',
    destinationName: 'United Arab Emirates',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from the UAE.',
    notes: 'Federal Authority for Identity, Citizenship, Customs and Port Security (ICP) standard.',
    source: 'UAE Federal Authority for Identity and Citizenship (ICP)',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'turkey',
    destinationName: 'Turkey',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 150,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Turkey.',
    notes: 'Turkish Directorate General of Migration Management. Some sources cite 5 months — 6 months is the safest standard.',
    source: 'Turkish Ministry of Foreign Affairs',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'saudi-arabia',
    destinationName: 'Saudi Arabia',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Saudi Arabia.',
    notes: 'Saudi Arabian immigration authorities require 6 months validity beyond the intended stay.',
    source: 'Saudi Ministry of Interior',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'egypt',
    destinationName: 'Egypt',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Egypt.',
    source: 'Egyptian Immigration Authority',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'mexico',
    destinationName: 'Mexico',
    ruleType: 'valid_for_duration',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay (6 months recommended)',
    ruleSummary: 'Mexico officially requires passport valid for the duration of stay, but many airlines apply a 6-month standard at check-in.',
    notes: 'Mexico\'s official requirement is valid for duration of stay, but given airline practices, 6 months beyond travel date is recommended.',
    source: 'Instituto Nacional de Migración (INM), Mexico',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'brazil',
    destinationName: 'Brazil',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Brazil.',
    source: 'Polícia Federal, Brazil',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'south-africa',
    destinationName: 'South Africa',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from South Africa.',
    notes: 'South Africa also requires at least 2 blank pages for immigration stamps.',
    source: 'South African Department of Home Affairs',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'philippines',
    destinationName: 'Philippines',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from the Philippines.',
    notes: 'Philippine Bureau of Immigration is strict — airlines are instructed to enforce this at check-in.',
    source: 'Bureau of Immigration, Philippines',
    lastVerified: '2026-01',
    confidence: 'High',
  },
  {
    destinationSlug: 'morocco',
    destinationName: 'Morocco',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Morocco.',
    source: 'Direction Générale de la Sûreté Nationale, Morocco',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'israel',
    destinationName: 'Israel',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your intended departure from Israel.',
    source: 'Israel Population and Immigration Authority',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'romania',
    destinationName: 'Romania',
    ruleType: 'three_months_beyond_stay',
    minimumValidityDays: 90,
    blankPagesRequired: 1,
    ruleLabel: '3 months beyond departure (EU standard)',
    ruleSummary: 'Romania applies EU standard passport validity rules. Passport must be valid for at least 3 months beyond your planned departure.',
    notes: 'Romania joined the Schengen Area air/sea space in 2024. The 3-month beyond departure rule applies.',
    source: 'Romanian Immigration Inspectorate',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'ukraine',
    destinationName: 'Ukraine',
    ruleType: 'other',
    minimumValidityDays: 90,
    blankPagesRequired: 1,
    ruleLabel: '3 months beyond intended departure (standard)',
    ruleSummary: 'Passport should typically be valid for at least 3 months beyond your planned departure date.',
    notes: 'Travel to Ukraine is subject to ongoing conflict-related restrictions. Verify current entry requirements from official government advisories before travel.',
    source: 'State Migration Service of Ukraine',
    lastVerified: '2026-01',
    confidence: 'Limited',
  },
  {
    destinationSlug: 'qatar',
    destinationName: 'Qatar',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Qatar.',
    source: 'Qatar Ministry of Interior',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'colombia',
    destinationName: 'Colombia',
    ruleType: 'valid_for_duration',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay (6 months recommended)',
    ruleSummary: 'Colombia officially requires passport valid for the duration of stay. 6 months validity beyond arrival is commonly recommended.',
    source: 'Migración Colombia',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'argentina',
    destinationName: 'Argentina',
    ruleType: 'valid_for_duration',
    minimumValidityDays: 90,
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must be valid for the entire duration of stay in Argentina.',
    source: 'Dirección Nacional de Migraciones, Argentina',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'chile',
    destinationName: 'Chile',
    ruleType: 'valid_for_duration',
    blankPagesRequired: 1,
    ruleLabel: 'Valid for duration of stay',
    ruleSummary: 'Passport must be valid for the full duration of your stay in Chile.',
    source: 'Extranjería y Migración, Chile',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'peru',
    destinationName: 'Peru',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 1,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Peru.',
    source: 'Superintendencia Nacional de Migraciones, Peru',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
  {
    destinationSlug: 'nigeria',
    destinationName: 'Nigeria',
    ruleType: 'six_months_beyond_stay',
    minimumValidityDays: 180,
    blankPagesRequired: 2,
    ruleLabel: '6 months beyond intended stay',
    ruleSummary: 'Passport must be valid for at least 6 months beyond your planned departure from Nigeria.',
    source: 'Nigeria Immigration Service',
    lastVerified: '2026-01',
    confidence: 'Medium',
  },
];

export function findValidityRule(destinationSlug: string): PassportValidityRule | undefined {
  return PASSPORT_VALIDITY_RULES.find(r => r.destinationSlug === destinationSlug);
}

export const SCHENGEN_SLUGS = new Set([
  'france', 'germany', 'italy', 'spain', 'netherlands', 'portugal', 'greece',
  'austria', 'belgium', 'switzerland', 'denmark', 'finland', 'norway', 'sweden',
  'czech-republic', 'poland', 'hungary', 'croatia', 'slovakia', 'slovenia',
  'estonia', 'latvia', 'lithuania', 'luxembourg', 'malta', 'iceland', 'liechtenstein',
]);
