/*
  # Update Australia Passport Complete Visa Requirements

  1. Updates for Australia Passport Holders
    - Fix all destination visa requirements with accurate, fact-checked data
    - Add bilateral visa waiver agreements for enhanced Schengen terms
    - Correct Brazil visa requirement (required since April 10, 2025)
    - Add New Zealand Trans-Tasman Travel Arrangement (indefinite residence)
    - Add Canada eTA requirement
    - Add China temporary visa-free arrangement details
    - Add Indonesia VoA requirement
    - Add Thailand 60-day visa-free stay (increased in 2024)
    - Add Turkey eVisa requirement
    - Add Vietnam eVisa requirement
    - Update all ETIAS information for Schengen countries
    - Set last_verified to 2026-02-19

  2. Key Corrections
    - Australia-Schengen Bilateral Agreements: Austria, Czech Republic, France, Germany, Greece, Italy, Netherlands, Poland, Portugal, Spain, Switzerland (90 days per entry regardless of other Schengen time)
    - Brazil: VISA REQUIRED since April 10, 2025 (reciprocity measure)
    - Canada: eTA required (not visa-free)
    - China: Temporary visa-free until Dec 31, 2026 (90 days since Sept 2025)
    - Indonesia: VoA or eVisa required (not simple visa-free)
    - New Zealand: Trans-Tasman - indefinite residence rights on arrival
    - Thailand: 60 days visa-free (increased from 30 in 2024)
    - Turkey: eVisa required (not visa-free)
    - UK: ETA required from April 2, 2025
    - USA: ESTA required under VWP with E-3 visa benefit
    - Vietnam: eVisa required (not visa-free)

  3. Affected Destinations
    All 42 destinations for Australia passport holders
*/

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral agreement for tourism or short business visits. 90 days within any 180-day period. Extendable once for additional 90 days at Migración (DNM). Return ticket may be requested. Proof of sufficient funds may be requested. Yellow fever certificate if arriving from endemic country. Entry smooth at all international airports and land borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'argentina';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Austria. IMPORTANT: 90 days per entry REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Travel insurance strongly recommended but not mandatory at border.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'austria';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested at border officers discretion. Travel insurance not a formal mandatory entry requirement at border.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'belgium';

UPDATE visa_rules SET visa_type = 'visa_required', visa_subtype = 'Tourist visa (VIVIS)', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'VISA REQUIRED as of April 10, 2025. Brazil reinstated visa requirements for Australian passport holders as reciprocity measure. Tourist visa must be obtained prior to travel via Brazilian government consular system or at Brazilian Embassy in Canberra or Consulate-General in Sydney. No visa on arrival available. Typically 90 days per visit. Passport valid 6 months beyond entry. Return ticket required. Proof of accommodation and funds required. Biometric fingerprinting on arrival. SIGNIFICANT CHANGE from pre-April 2025 visa-free arrangement.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'brazil';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eTA', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'eTA (Electronic Travel Authorization) MANDATORY before boarding any flight to Canada. Apply at canada.ca/eta. Fee CAD 7. Usually approved within minutes. Valid 5 years or until passport expiry. Multiple entries. Max stay: up to 6 months per visit at border officer discretion. Entry by land or sea does not require eTA. Proof of funds, return ticket, and ties to Australia may be requested. Biometric fingerprinting at border. Working Holiday Visa arrangement for ages 18-35. Australia-Canada consular services sharing agreement.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'canada';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. 90 days within any 180-day period. Return ticket may be requested. Proof of funds may be requested at land borders. Yellow fever certificate if arriving from endemic country. Working holiday visa available for ages 18-35. Entry seamless at all international airports and land borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'chile';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Temporary arrangement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'TEMPORARY bilateral visa-free arrangement valid from July 1, 2024 to December 31, 2026. Up to 90 days per visit (increased from 15 days since September 17, 2025). Outside this window, standard tourist (L) or business (M) visa required. Verify arrangement extension before booking beyond Dec 2026. Passport valid 6 months beyond entry. Return ticket required. Proof of hotel booking or invitation letter required. Biometric fingerprinting on arrival. Australian government advises heightened detention risks under Chinese national security laws.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'china';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business visits. 90 days within any 180-day period. Extendable once for additional 90 days at Migración Colombia. Return ticket may be requested. Yellow fever certificate if arriving from endemic country. Proof of funds may be requested. No biometric enrollment for tourists. Digital migration check standard on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'colombia';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules (Croatia joined Schengen January 2023). 90 days within any 180-day period across Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and onward travel may be requested at border officers discretion. Schengen fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'croatia';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Czech Republic. IMPORTANT: 90 days per entry REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and return ticket may be requested. Schengen biometric checks at external entry points.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'czech-republic';

UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or e-Visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa on arrival at major Egyptian international airports. E-Visa also available at visa2egypt.gov.eg, apply at least 7 days before travel. 30 days per entry. Maximum 3 entries and no more than 90 days total per calendar year. Visa fee USD 25 (payable in USD, EUR, or GBP at airport). Return ticket required. Hotel reservation confirmation required. Proof of sufficient funds required. Biometrics may be collected on arrival. E-Visa processed within 5-7 business days.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'egypt';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with France. IMPORTANT: 90 days in France per entry REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'france';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Germany. IMPORTANT: 90 days per entry in Germany REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be verified. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'germany';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Greece. IMPORTANT: 90 days per entry in Greece REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and return ticket may be requested at border officers discretion. Schengen fingerprinting at external border crossings.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'greece';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and onward travel may be requested. Schengen biometric checks at external entry points.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'hungary';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'e-Tourist Visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'E-Tourist Visa (e-TV) required. Apply at indianvisaonline.gov.in at least 4 days before arrival and no more than 120 days in advance. 30 days per visit. Maximum 2 e-Tourist Visas per calendar year. 1-year or 5-year e-Tourist Visa with longer stays also available at higher fee. Fee USD 25 for 30-day variant. Passport must have at least 2 blank pages. Must arrive via one of 32 designated airports or 5 seaports. Processing 72-96 hours. Return ticket required. Proof of funds and accommodation required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'india';

UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or eVisa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa on Arrival (VoA) or eVisa required — NO blanket visa-free entry for Australians. VoA (IDR 500,000, approx. USD 30) available at designated airports including Bali (Ngurah Rai), Jakarta, Surabaya. eVisa also available via molina.imigrasi.go.id. 30 days per visit. Extendable once for additional 30 days at local immigration office. Passport must have at least one blank page. Return ticket required. Yellow fever certificate if arriving from endemic country. VoA payable in cash (IDR or USD) or card at immigration counter. Biometric fingerprinting on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'indonesia';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Italy. IMPORTANT: 90 days per entry in Italy REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and return ticket may be requested. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'italy';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business visits (granted December 1998 under bilateral agreement). 90 days per visit. Persons previously sentenced to 1+ year imprisonment not eligible and must obtain visa. Return ticket required. Proof of sufficient funds and accommodation required. Biometric fingerprinting and photograph on arrival. Departure tax (JPY 1,000) collected by airline. Working Holiday Visa arrangement for ages 18-30. Japan Visit Web (digital declaration) should be completed before landing. Entry straightforward at all international airports.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'japan';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. 90 days per visit. Passport valid at least 6 months. Return ticket may be requested. Biometric fingerprinting on arrival and departure at all international entry points. Malaysia My Second Home (MM2H) visa available for long-term stays — Australia is designated country for MM2H. Entry efficient at all international airports.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'malaysia';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free for tourism, transit, or short business stays. Up to 180 days for tourism. Actual duration at immigration officer discretion written on FMM form. Multiple Immigration Form (FMM) must be completed on arrival or in advance. FMM included in airfare for air travel; fees apply for land entry stays exceeding 7 days. Working Holiday Visa arrangement for ages 18-35. Entry smooth at all international airports and land borders. FMM must be retained and collected on departure.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'mexico';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Netherlands. IMPORTANT: 90 days per entry in European Netherlands REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Schengen biometric fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'netherlands';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Trans-Tasman (indefinite)', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'UNIQUE PRIVILEGED STATUS under Trans-Tasman Travel Arrangement. Australian citizens granted New Zealand Resident Visa on arrival entitling them to live, work, and study in NZ INDEFINITELY, provided character requirements met. NO NZeTA, NO IVL (NZD 35 levy), NO visitor visa required. Valid Australian passport sufficient. No minimum validity rule. Automated eGates at major NZ airports. Character requirements apply — serious criminal convictions may result in refusal. May apply for NZ citizenship after 5 years residence. Most seamless entry of any international destination for Australians. One of world''s most liberal bilateral immigration frameworks.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'new-zealand';

UPDATE visa_rules SET visa_type = 'visa_required', visa_subtype = 'eVisa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa required prior to travel. Nigeria does not offer visa on arrival for Australians. eVisa most convenient option at portal.immigration.gov.ng or apply at Nigerian High Commission in Canberra. Processing typically 2-3 business days for eVisa. Typically 30 days for tourist visa, extendable at Nigeria Immigration Service. Passport valid at least 6 months with at least 2 blank pages. Return ticket required. Proof of hotel booking or invitation letter required. Yellow fever certificate strongly recommended. Apply at least 2 weeks before travel. Biometrics collected on arrival at Lagos and Abuja airports.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'nigeria';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism stays. Entry granted on arrival. 30 days on arrival. Extendable at Bureau of Immigration to maximum 59 days, then further in monthly increments up to 3 years. Passport valid at least 6 months beyond departure. Return ticket required. Proof of sufficient funds and accommodation required. Yellow fever certificate if arriving from endemic country. Australia-Philippines maintain strong bilateral people-to-people ties with large Filipino-Australian community. Entry simple at all international airports. Biometric data collected on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'philippines';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Poland. IMPORTANT: 90 days per entry in Poland REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Schengen biometric fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'poland';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Portugal. IMPORTANT: 90 days per entry in Portugal REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Portugal D7 Passive Income Visa, Digital Nomad Visa (D8), and Golden Visa popular for Australians. Working Holiday Arrangement for ages 18-35. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'portugal';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. Free visa on arrival stamp issued at Hamad International Airport. 30 days per visit. Extendable at General Directorate of Passports. Return ticket required. Proof of hotel booking or sufficient funds required. Biometric iris scanning and fingerprinting on arrival. Entry seamless. All visitors subject to customs and security screening.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'qatar';

UPDATE visa_rules SET visa_type = 'visa_required', visa_subtype = 'Tourist visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'Tourist visa required prior to travel, obtainable from Russian Embassy in Canberra or Consulate-General in Sydney. No visa on arrival. Invitation letter (tourist voucher from registered Russian travel agency) required. 30 days for standard tourist visa. CRITICAL: Australian Government advises DO NOT TRAVEL to Russia due to arbitrary detention risk, ongoing Ukraine conflict, and severely limited consular assistance. Registration with local authorities (hotel or OVIR) within 7 business days mandatory. Direct flights severely limited due to airspace restrictions. Apply well in advance. DFAT warns ability to provide consular assistance is severely limited.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'russia';

UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or eVisa', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 6, return_ticket_required = true, insurance_required = true, sufficient_funds_required = true, notes = 'Saudi tourist visa on arrival at designated entry points or eVisa at visa.visitsaudi.com. Up to 90 days per year (single or multiple visits). eVisa application can be submitted up to 30 days before travel. Return ticket required. Hotel booking required. Travel insurance required (included in eVisa). Biometric iris scanning and fingerprinting on arrival. Non-Muslim visitors prohibited from entering Mecca. eVisa valid 1 year, multiple entries. Cost approximately USD 80 (includes mandatory health insurance). Approval within minutes to few days. Modest dress standards expected.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'saudi-arabia';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. 30 days per visit. Extendable at Immigration and Checkpoints Authority (ICA) before authorized stay expires. APEC Business Travel Card (ABTC) available for eligible business travelers. Return ticket strongly recommended. Proof of funds and accommodation may be requested. Biometric fingerprinting and photo on arrival and departure. Singapore strictly enforces immigration laws. Automated eGates available at Changi Airport. SG Arrival Card app declaration before landing. Australia-Singapore have strong bilateral ties with numerous corporate immigration pathways.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'singapore';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 1, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free for tourism, transit, or short business stays. 30 days per visit. Passport valid at least 1 month beyond departure with minimum 2 blank pages for stamps. Yellow fever certificate required if arriving from or transiting through endemic country. Return ticket recommended. Biometric enrollment on arrival. Entry straightforward at OR Tambo International (Johannesburg), Cape Town International, and other major ports. Travel insurance strongly recommended.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'south-africa';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'K-ETA', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free but K-ETA (Korea Electronic Travel Authorization) MANDATORY before travel. Apply at k-eta.go.kr at least 72 hours before departure. Fee KRW 10,000 (approx. USD 7). Valid 3 years for multiple entries. Up to 90 days within any 12-month period. Return ticket required. Proof of funds and accommodation may be requested. Biometric fingerprinting and photo on arrival. Persons with 1+ year imprisonment not eligible. Working Holiday Visa arrangement for ages 18-30. Automated eGates at Incheon, Gimpo, and major airports for enrolled travelers. K-ETA approved within 72 hours.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'south-korea';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Spain. IMPORTANT: 90 days per entry in Spain REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and return ticket may be requested. Spain Non-Lucrative Visa (NLV) and Digital Nomad Visa popular for Australians. Working Holiday Visa arrangement for ages 18-35. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'spain';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Bilateral agreement', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral visa waiver agreement with Switzerland. IMPORTANT: 90 days per entry in Switzerland REGARDLESS of time spent in other Schengen countries — more favorable than standard Schengen 90/180 rule. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 will apply to Switzerland as Schengen member (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Switzerland is non-EU Schengen member but enforces same rules. Schengen biometric fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'switzerland';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 60, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism stays. Entry granted on arrival. 60 days per visit (INCREASED from 30 days in 2024 under Thailand tourism promotion policy). Extendable once for additional 30 days at local immigration office (THB 1,900 fee). Passport valid at least 6 months. Return ticket expected by immigration. Proof of funds (THB 20,000 per person or 40,000 per family) may be requested. Biometric fingerprinting on arrival. Yellow fever certificate if from endemic country. Thailand Digital Arrival Card (TDAC) may be required. Working Holiday Visa arrangement for ages 18-30. Thailand is one of most visited destinations for Australians globally.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'thailand';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisa', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'eVisa REQUIRED before or upon arrival. eVisa available at evisa.gov.tr. Apply at least 48 hours before travel. Fee USD 60 for Australian citizens. Valid for 180 days from issue, single entry. 90 days within any 180-day period. Visa on arrival available at major airports but eVisa STRONGLY preferred to avoid queues. Passport valid at least 6 months. Return ticket not formally required but may be requested. Proof of accommodation may be requested. Biometric data collected on arrival. eVisa approval usually within minutes to few hours. E-gates available for re-entry at some airports for enrolled travelers.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'turkey';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Free visa on arrival stamp at any UAE port of entry. 30 days per visit. Extendable for additional 30 days through GDRFA (General Directorate of Residency and Foreigners Affairs). Return ticket required. Proof of sufficient funds and hotel booking required. Biometric iris scanning and fingerprinting on arrival at all UAE ports. Entry seamless at Dubai International, Abu Dhabi International, and all other UAE airports. Australia-UAE maintain strong bilateral business and trade relationship. Visa extension applications online or at GDRFA offices.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'united-arab-emirates';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'UK ETA', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'UK Electronic Travel Authorisation (ETA) MANDATORY from April 2, 2025. Apply via UK ETA app or online at gov.uk. Fee GBP 16 (approx. USD 20). Valid 2 years or until passport expiry. Multiple entries. Up to 6 months per visit. Return ticket may be requested. Proof of funds and purpose of visit may be verified. Biometric checks at UK border. eGates at Heathrow, Gatwick, and major airports for Australian passport holders. Youth Mobility Scheme (Working Holiday Visa) for ages 18-35, extended to allow stays up to 3 years. ETA approved within hours (up to 3 business days). Australia-UK have very close bilateral ties with high traveler volumes.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'united-kingdom';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'ESTA', max_stay_days = 90, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'ESTA (Electronic System for Travel Authorization) MANDATORY under Visa Waiver Program (VWP). Apply at esta.cbp.dhs.gov at least 72 hours before departure. Fee USD 21. Valid 2 years or until passport expiry. Up to 90 days per visit. Cannot be extended under VWP. Passport must be e-passport (biometric chip). Return ticket required. Biometric fingerprinting and photo on arrival. CBP conducts thorough entry interviews. CRITICAL: Overstaying even 1 day permanently forfeits ESTA eligibility. Persons who traveled to Iran, Iraq, Libya, North Korea, Somalia, Sudan, Syria, or Yemen since March 1, 2011 ineligible for ESTA. MAJOR BENEFIT: E-3 visa exclusively for Australian nationals — much faster processing and lower demand than H-1B, highly attractive for skilled professionals. E-3 visa is significant bilateral benefit for Australians.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'united-states';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisa', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'eVisa REQUIRED before travel. Apply at evisa.xuatnhapcanh.gov.vn. Fee USD 25. Valid 90 days, multiple entries. Apply at least 3 business days before travel (allow more during peak periods). Visa on arrival technically available but requires pre-approval letter and generally only suitable for air travel — eVisa STRONGLY recommended. Passport valid at least 6 months. Return ticket may be requested. Proof of accommodation and funds may be requested. eVisa straightforward online application, approved within 3 business days. Arrival smooth at Noi Bai (Hanoi), Tan Son Nhat (HCMC), Da Nang, and all major ports.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'australia' AND destination_slug = 'vietnam';
