/*
  # Add Morocco Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Moroccan passport holders traveling to all 51 active destinations.

  ## Morocco Passport Profile
  - Mid-tier African passport with ~65-70 visa-free destinations
  - Strong access to Arab League countries
  - Some visa-free access to EU/Schengen (limited compared to Western passports)
  - Visa required for US, Canada, UK, Australia
  - Important player in Africa-EU relations

  ## Key Notes
  - Morocco has strong bilateral ties with France and Spain
  - Arab League membership provides regional access
  - Abraham Accords: Morocco normalized relations with Israel (2020)
  - Schengen visa required for most EU travel

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
-- Schengen - VISA REQUIRED for Morocco (unlike Western passports)
(gen_random_uuid(), 'morocco', 'austria', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Austrian Embassy/Consulate. Short-stay C visa for 90 days max.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.bmeia.gv.at', '2026-02-24', 'Moroccan passport holders require a Schengen visa to visit Austria. Apply at Austrian Embassy. Strong ties due to Moroccan diaspora. Approval rates moderate.'),
(gen_random_uuid(), 'morocco', 'belgium', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Belgian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://dofi.ibz.be', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Belgium. Large Moroccan community in Belgium. Apply at Belgian Embassy.'),
(gen_random_uuid(), 'morocco', 'croatia', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Croatian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://mup.gov.hr', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Croatia.'),
(gen_random_uuid(), 'morocco', 'czech-republic', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Czech Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mvcr.cz', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Czech Republic.'),
(gen_random_uuid(), 'morocco', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'morocco', 'finland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Finnish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Finland.'),
(gen_random_uuid(), 'morocco', 'france', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at French Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://france-visas.gouv.fr', '2026-02-24', 'Moroccan passport holders require a Schengen visa for France. Largest Moroccan diaspora in Europe. Bilateral ties are strong. Apply at VFS or French consulate.'),
(gen_random_uuid(), 'morocco', 'germany', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at German Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.bmi.bund.de', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Germany. Large Moroccan community. Apply at German Embassy.'),
(gen_random_uuid(), 'morocco', 'greece', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Greek Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.ypes.gr', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Greece.'),
(gen_random_uuid(), 'morocco', 'hungary', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Hungarian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.kormany.hu', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Hungary.'),
(gen_random_uuid(), 'morocco', 'italy', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Italian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.interno.gov.it', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Italy. Large Moroccan community in Italy.'),
(gen_random_uuid(), 'morocco', 'netherlands', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Dutch Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://ind.nl', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Netherlands. Large Moroccan community in Netherlands.'),
(gen_random_uuid(), 'morocco', 'norway', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Norwegian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.udi.no', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Norway.'),
(gen_random_uuid(), 'morocco', 'poland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Polish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Poland.'),
(gen_random_uuid(), 'morocco', 'portugal', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Portuguese Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.sef.pt', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Portugal.'),
(gen_random_uuid(), 'morocco', 'spain', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Spanish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.interior.gob.es', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Spain. Spain and Morocco share a land border (Ceuta/Melilla). Strong bilateral ties.'),
(gen_random_uuid(), 'morocco', 'sweden', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Swedish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Sweden.'),
(gen_random_uuid(), 'morocco', 'switzerland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Swiss Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.sem.admin.ch', '2026-02-24', 'Moroccan passport holders require a Schengen visa for Switzerland.'),
-- EU non-Schengen - also visa required
(gen_random_uuid(), 'morocco', 'ireland', 'visa_required', NULL, NULL, NULL, 'Irish Short Stay (C) visa required. Apply at Irish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Moroccan passport holders require an Irish Short Stay visa. Apply through INIS online system.'),
(gen_random_uuid(), 'morocco', 'romania', 'visa_required', NULL, NULL, NULL, 'Schengen/Romanian visa required. Apply at Romanian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Moroccan passport holders require a visa for Romania.'),
-- UK - visa required
(gen_random_uuid(), 'morocco', 'united-kingdom', 'visa_required', NULL, NULL, NULL, 'Standard visitor visa required. Apply through UK Visas and Immigration.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.gov.uk/standard-visitor-visa', '2026-02-24', 'Moroccan passport holders require a UK Standard Visitor Visa. Apply through UKVI. Biometric appointment required. Large Moroccan community in UK.'),
-- Americas - mostly visa required
(gen_random_uuid(), 'morocco', 'argentina', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Argentina.'),
(gen_random_uuid(), 'morocco', 'brazil', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Brazilian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Brazilian visa required for Moroccan passport holders. Apply at Brazilian Embassy.'),
(gen_random_uuid(), 'morocco', 'canada', 'visa_required', NULL, NULL, NULL, 'Temporary Resident Visa (TRV) required. Apply through IRCC online.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html', '2026-02-24', 'Moroccan passport holders require a Canadian TRV. Large Moroccan community in Canada (Quebec especially).'),
(gen_random_uuid(), 'morocco', 'chile', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Chile.'),
(gen_random_uuid(), 'morocco', 'colombia', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Colombia.'),
(gen_random_uuid(), 'morocco', 'mexico', 'visa_required', NULL, NULL, NULL, 'Visa required for Moroccan passport holders entering Mexico.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Mexican visa required for Moroccan passport holders. Apply at Mexican Embassy/Consulate.'),
(gen_random_uuid(), 'morocco', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'morocco', 'united-states', 'visa_required', NULL, NULL, NULL, 'B-1/B-2 visitor visa required. Apply at US Embassy Rabat or Casablanca.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html', '2026-02-24', 'Moroccan passport holders require a US visitor visa. Apply at Embassy in Rabat or Consulate in Casablanca. Long wait times possible.'),
-- Arab/Middle East - generally visa-free or on arrival
(gen_random_uuid(), 'morocco', 'egypt', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival for Arab League members.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Egypt under Arab League agreements.'),
(gen_random_uuid(), 'morocco', 'qatar', 'visa_free', NULL, 90, NULL, '90 days visa-free.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Qatar under Arab League agreements.'),
(gen_random_uuid(), 'morocco', 'saudi-arabia', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply through Saudi embassy or online portal.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visa.visitsaudi.com', '2026-02-24', 'Saudi visa required for Moroccan passport holders. Tourist eVisa may be available. Apply through Saudi embassy or online portal.'),
(gen_random_uuid(), 'morocco', 'united-arab-emirates', 'visa_on_arrival', NULL, 30, NULL, '30 days visa on arrival, free of charge.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'Moroccan passport holders can get free visa on arrival in UAE for up to 30 days. Strong bilateral ties.'),
(gen_random_uuid(), 'morocco', 'israel', 'visa_free', NULL, 90, NULL, '90 days visa-free under Abraham Accords normalization (2020).', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Morocco normalized relations with Israel via Abraham Accords (2020). Moroccan passport holders enjoy visa-free access. Direct flights available.'),
-- Africa
(gen_random_uuid(), 'morocco', 'nigeria', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Nigerian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://portal.immigration.gov.ng', '2026-02-24', 'Nigerian visa required for Moroccan passport holders. Apply in advance. Yellow fever certificate mandatory.'),
(gen_random_uuid(), 'morocco', 'south-africa', 'visa_required', NULL, NULL, NULL, 'Visitor visa required. Apply at South African Embassy/Consulate.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'South African visitor visa required for Moroccan passport holders. Apply at South African Embassy.'),
-- Asia
(gen_random_uuid(), 'morocco', 'australia', 'visa_required', NULL, NULL, NULL, 'Visitor visa required (subclass 600). Apply through ImmiAccount.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600', '2026-02-24', 'Moroccan passport holders require a Visitor visa (subclass 600) for Australia. Apply online. Processing times vary.'),
(gen_random_uuid(), 'morocco', 'china', 'visa_free', NULL, 30, NULL, '30 days visa-free under bilateral agreement. Extended to 30 days in 2024.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China signed visa-free agreement with Morocco. Moroccan passport holders can visit for up to 30 days without a visa.'),
(gen_random_uuid(), 'morocco', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Moroccan passport holders can obtain Indian eVisa. Apply at least 4 days before travel.'),
(gen_random_uuid(), 'morocco', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available at major airports. Single entry, tourist only.'),
(gen_random_uuid(), 'morocco', 'japan', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Japanese Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Japanese visa required for Moroccan passport holders. Apply at Japanese Embassy. Processing 5-7 business days.'),
(gen_random_uuid(), 'morocco', 'malaysia', 'visa_free', NULL, 30, NULL, '30 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Malaysia. Majority Muslim country connection.'),
(gen_random_uuid(), 'morocco', 'new-zealand', 'visa_required', NULL, NULL, NULL, 'Visitor visa required. Apply through Immigration New Zealand.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.immigration.govt.nz', '2026-02-24', 'Moroccan passport holders require a visitor visa for New Zealand.'),
(gen_random_uuid(), 'morocco', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable through Bureau of Immigration.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Moroccan passport holders receive 30-day visa-free entry to Philippines.'),
(gen_random_uuid(), 'morocco', 'russia', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Russian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://electronic-visa.kdmid.ru', '2026-02-24', 'Russian visa required for Moroccan passport holders. Travel advisory in place.'),
(gen_random_uuid(), 'morocco', 'singapore', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Singapore Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Singaporean visa required for Moroccan passport holders. Apply at ICA or Singapore Embassy.'),
(gen_random_uuid(), 'morocco', 'south-korea', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Korean Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.kr', '2026-02-24', 'South Korean visa required for Moroccan passport holders. Apply at Korean Embassy.'),
(gen_random_uuid(), 'morocco', 'thailand', 'visa_free', NULL, 30, NULL, '30 days visa exemption.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Moroccan passport holders enjoy visa-free entry to Thailand for 30 days.'),
(gen_random_uuid(), 'morocco', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Moroccan passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Check official advisories.'),
(gen_random_uuid(), 'morocco', 'vietnam', 'visa_free', NULL, 45, NULL, '45 days visa-free for tourism.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Moroccan passport holders enjoy visa-free access to Vietnam for 45 days.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
