/*
  # Add Inbound Visa Rules for 10 New Destination Countries

  ## Overview
  Adds visa rules for all major existing passports (US, UK, Canada, Australia, India, Japan,
  China, Brazil, Argentina, South Africa, Nigeria, etc.) traveling TO the 10 new destinations:
  Denmark, Finland, Ireland, Israel, Morocco, Norway, Peru, Romania, Sweden, Ukraine.

  ## Passport Groups Covered
  1. USA, UK, Canada, Australia, New Zealand - high-power Western passports
  2. Japan, South Korea, Singapore - high-power Asian passports
  3. India, China, Philippines, Indonesia, Vietnam - large Asian populations
  4. Brazil, Argentina, Chile, Colombia, Mexico - Latin American
  5. South Africa, Nigeria, Egypt - African passports
  6. Qatar, UAE, Saudi Arabia - Gulf states
  7. Russia, Turkey, Malaysia, Thailand - other key markets

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES

-- =====================================================
-- DENMARK as destination
-- =====================================================
-- US to Denmark (Schengen)
(gen_random_uuid(), 'united-states', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'US passport holders enjoy visa-free access to Denmark under Schengen visa waiver.'),
(gen_random_uuid(), 'united-kingdom', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Post-Brexit.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'UK passport holders enjoy visa-free access to Denmark post-Brexit. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'canada', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'australia', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Australian passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'new-zealand', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'New Zealand passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'japan', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'south-korea', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'singapore', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Singaporean passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'brazil', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'argentina', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Argentine passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'chile', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Chilean passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'mexico', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Mexican passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'colombia', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Colombian passport holders enjoy visa-free access to Denmark under EU-Colombia agreement.'),
(gen_random_uuid(), 'india', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate or VFS Global.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Indian passport holders require a Schengen visa for Denmark. Apply at VFS Global or Danish Embassy.'),
(gen_random_uuid(), 'china', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Chinese passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'nigeria', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Nigerian passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'south-africa', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'South African passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'russia', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy. Note: restrictions due to geopolitical situation.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Russian passport holders require a Schengen visa. Visa issuance significantly restricted since 2022 conflict.'),
(gen_random_uuid(), 'turkey', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Turkish passport holders require a Schengen visa for Denmark. Apply at Danish Embassy.'),
(gen_random_uuid(), 'indonesia', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Indonesian passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'philippines', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Filipino passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'vietnam', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Vietnamese passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'egypt', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Egyptian passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'malaysia', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'thailand', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Thai passport holders require a Schengen visa for Denmark.'),
(gen_random_uuid(), 'qatar', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'united-arab-emirates', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'UAE passport holders enjoy visa-free access to Denmark.'),
(gen_random_uuid(), 'saudi-arabia', 'denmark', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Danish Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Saudi passport holders require a Schengen visa for Denmark.'),

-- =====================================================
-- FINLAND as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'US passport holders enjoy visa-free access to Finland under Schengen visa waiver.'),
(gen_random_uuid(), 'united-kingdom', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Post-Brexit.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'UK passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'canada', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'australia', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Australian passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'japan', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'south-korea', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'brazil', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'india', 'finland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Finnish Embassy/VFS Global.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Indian passport holders require a Schengen visa for Finland.'),
(gen_random_uuid(), 'china', 'finland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Finnish Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Chinese passport holders require a Schengen visa for Finland.'),
(gen_random_uuid(), 'nigeria', 'finland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Finnish Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Nigerian passport holders require a Schengen visa for Finland.'),
(gen_random_uuid(), 'south-africa', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'South African passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'russia', 'finland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Finland shares border with Russia. Land border largely closed since 2022.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Russian passport holders require Schengen visa. Finland-Russia land border has significant restrictions since 2022 conflict.'),
(gen_random_uuid(), 'turkey', 'finland', 'visa_required', NULL, NULL, NULL, 'Schengen visa required.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://migri.fi', '2026-02-24', 'Turkish passport holders require a Schengen visa for Finland.'),
(gen_random_uuid(), 'malaysia', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'qatar', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Finland.'),
(gen_random_uuid(), 'united-arab-emirates', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'UAE passport holders enjoy visa-free access to Finland.'),

-- =====================================================
-- IRELAND as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'US passport holders enjoy visa-free access to Ireland. Large Irish-American community.'),
(gen_random_uuid(), 'canada', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'australia', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Australian passport holders enjoy visa-free access to Ireland. Large Irish-Australian community.'),
(gen_random_uuid(), 'new-zealand', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'New Zealand passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'japan', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'south-korea', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'singapore', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Singaporean passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'brazil', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'india', 'ireland', 'visa_required', NULL, NULL, NULL, 'Irish Short Stay (C) visa required. Apply through INIS.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Indian passport holders require an Irish visa. Large Indian community in Ireland. Apply through IrishImmigration.ie.'),
(gen_random_uuid(), 'china', 'ireland', 'visa_required', NULL, NULL, NULL, 'Irish Short Stay (C) visa required. Apply through INIS.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Chinese passport holders require an Irish visa.'),
(gen_random_uuid(), 'nigeria', 'ireland', 'visa_required', NULL, NULL, NULL, 'Irish Short Stay (C) visa required. Apply through INIS.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Nigerian passport holders require an Irish visa. Large Nigerian community in Ireland.'),
(gen_random_uuid(), 'south-africa', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'South African passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'malaysia', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'qatar', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'united-arab-emirates', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'UAE passport holders enjoy visa-free access to Ireland.'),
(gen_random_uuid(), 'turkey', 'ireland', 'visa_required', NULL, NULL, NULL, 'Irish Short Stay (C) visa required.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Turkish passport holders require an Irish visa.'),
(gen_random_uuid(), 'mexico', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Mexican passport holders enjoy visa-free access to Ireland.'),

-- =====================================================
-- ISRAEL as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'US passport holders enjoy visa-free access to Israel. Strong US-Israel bilateral relations.'),
(gen_random_uuid(), 'canada', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Israel.'),
(gen_random_uuid(), 'australia', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Australian passport holders enjoy visa-free access to Israel.'),
(gen_random_uuid(), 'new-zealand', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'New Zealand passport holders enjoy visa-free access to Israel.'),
(gen_random_uuid(), 'japan', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Israel.'),
(gen_random_uuid(), 'south-korea', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Israel.'),
(gen_random_uuid(), 'india', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Indian passport holders enjoy visa-free access to Israel. Strong India-Israel bilateral relations.'),
(gen_random_uuid(), 'china', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Chinese passport holders enjoy visa-free access to Israel under bilateral agreement.'),
(gen_random_uuid(), 'brazil', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Israel.'),
(gen_random_uuid(), 'russia', 'israel', 'visa_free', NULL, 90, 180, '90 days per 180-day period under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Russian passport holders enjoy visa-free access to Israel under bilateral agreement. Large Russian-speaking Jewish community.'),
(gen_random_uuid(), 'nigeria', 'israel', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Israeli Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Nigerian passport holders require a visa for Israel. Apply at Israeli Embassy.'),
(gen_random_uuid(), 'egypt', 'israel', 'visa_free', NULL, 90, NULL, '90 days under Egypt-Israel peace treaty provisions.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Egyptian passport holders can enter Israel under Egypt-Israel peace treaty (1979). Entry via Sinai, Taba, or Egyptian-Israeli crossings.'),
(gen_random_uuid(), 'turkey', 'israel', 'visa_required', NULL, NULL, NULL, 'Visa required. Relations have been historically tense. Check current status.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Turkish passport holders require a visa for Israel. Diplomatic relations have been complicated. Check current status.'),

-- =====================================================
-- NORWAY as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'US passport holders enjoy visa-free access to Norway under Schengen visa waiver.'),
(gen_random_uuid(), 'united-kingdom', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Post-Brexit.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'UK passport holders enjoy visa-free access to Norway post-Brexit. Subject to 90/180 Schengen rule.'),
(gen_random_uuid(), 'canada', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'australia', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Australian passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'japan', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'south-korea', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'brazil', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'india', 'norway', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Norwegian Embassy/VFS Global.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.udi.no', '2026-02-24', 'Indian passport holders require a Schengen visa for Norway.'),
(gen_random_uuid(), 'china', 'norway', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Norwegian Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.udi.no', '2026-02-24', 'Chinese passport holders require a Schengen visa for Norway.'),
(gen_random_uuid(), 'russia', 'norway', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Norway-Russia land border at Storskog (significantly restricted since 2022).', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.udi.no', '2026-02-24', 'Russian passport holders require Schengen visa. Norway shares a short land border with Russia. Significant restrictions since 2022.'),
(gen_random_uuid(), 'malaysia', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'qatar', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Norway.'),
(gen_random_uuid(), 'united-arab-emirates', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'UAE passport holders enjoy visa-free access to Norway.'),

-- =====================================================
-- SWEDEN as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'US passport holders enjoy visa-free access to Sweden under Schengen visa waiver.'),
(gen_random_uuid(), 'united-kingdom', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Post-Brexit.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'UK passport holders enjoy visa-free access to Sweden post-Brexit.'),
(gen_random_uuid(), 'canada', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'australia', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Australian passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'japan', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'south-korea', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'brazil', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'india', 'sweden', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Swedish Embassy/VFS Global.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Indian passport holders require a Schengen visa for Sweden.'),
(gen_random_uuid(), 'china', 'sweden', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Swedish Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Chinese passport holders require a Schengen visa for Sweden.'),
(gen_random_uuid(), 'nigeria', 'sweden', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Apply at Swedish Embassy.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Nigerian passport holders require a Schengen visa for Sweden.'),
(gen_random_uuid(), 'russia', 'sweden', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Restrictions in place since 2022.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Russian passport holders require a Schengen visa. Significant restrictions since 2022.'),
(gen_random_uuid(), 'malaysia', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'qatar', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Sweden.'),
(gen_random_uuid(), 'united-arab-emirates', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'UAE passport holders enjoy visa-free access to Sweden.'),

-- =====================================================
-- ROMANIA as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'US passport holders enjoy visa-free access to Romania. Romania joined Schengen in 2024.'),
(gen_random_uuid(), 'united-kingdom', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day period. Post-Brexit.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'UK passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'canada', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'australia', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Australian passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'japan', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'south-korea', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'brazil', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'india', 'romania', 'visa_required', NULL, NULL, NULL, 'Schengen/Romanian visa required. Apply at Romanian Embassy/VFS.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Indian passport holders require a Schengen visa for Romania. Large Indian tech community in Romania.'),
(gen_random_uuid(), 'china', 'romania', 'visa_required', NULL, NULL, NULL, 'Schengen/Romanian visa required.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Chinese passport holders require a visa for Romania.'),
(gen_random_uuid(), 'nigeria', 'romania', 'visa_required', NULL, NULL, NULL, 'Schengen/Romanian visa required.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Nigerian passport holders require a visa for Romania.'),
(gen_random_uuid(), 'russia', 'romania', 'visa_required', NULL, NULL, NULL, 'Schengen visa required. Restrictions in place since 2022.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Russian passport holders require a Schengen visa for Romania. Significant restrictions since 2022 conflict. Romania shares border with Ukraine.'),
(gen_random_uuid(), 'malaysia', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'qatar', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Romania.'),
(gen_random_uuid(), 'united-arab-emirates', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'UAE passport holders enjoy visa-free access to Romania.'),

-- =====================================================
-- UKRAINE as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'US passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. US government advises against travel to Ukraine. Check advisories.'),
(gen_random_uuid(), 'canada', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Canadian passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Canada advises against travel.'),
(gen_random_uuid(), 'australia', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Australian passport holders enjoy visa-free access. Active armed conflict. Do not travel advisory in effect.'),
(gen_random_uuid(), 'japan', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Japanese passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Check Japanese government advisories.'),
(gen_random_uuid(), 'india', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Indian passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. India has significant national interests in both Russia and Ukraine. Check advisories.'),
(gen_random_uuid(), 'china', 'ukraine', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Ukrainian Embassy. Active conflict makes travel inadvisable.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visitukraine.today', '2026-02-24', 'Chinese passport holders require a visa for Ukraine. Active armed conflict. Check advisories.'),
(gen_random_uuid(), 'brazil', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Brazilian passport holders enjoy visa-free access. Active armed conflict. Check advisories.'),
(gen_random_uuid(), 'turkey', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Turkish passport holders enjoy visa-free access. Turkey has maintained relations with both Russia and Ukraine. Active conflict - check advisories.'),
(gen_random_uuid(), 'russia', 'ukraine', 'restricted', NULL, NULL, NULL, 'Entry not permitted. Russia is at war with Ukraine. No diplomatic relations.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://mfa.gov.ua', '2026-02-24', 'Russian passport holders cannot enter Ukraine. Active armed conflict. Ukrainian government does not allow entry by Russian citizens under current circumstances.'),
(gen_random_uuid(), 'malaysia', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Malaysian passport holders enjoy visa-free access. Active armed conflict.'),

-- =====================================================
-- PERU as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'US passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'united-kingdom', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'UK passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'canada', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'australia', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Australian passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'japan', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Japanese passport holders enjoy visa-free access. Large Japanese-Peruvian community (Nikkei).'),
(gen_random_uuid(), 'south-korea', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'china', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Chinese passport holders enjoy visa-free access to Peru under bilateral agreement. Large Chinese-Peruvian community.'),
(gen_random_uuid(), 'india', 'peru', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Peruvian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Indian passport holders require a visa for Peru. Apply at Peruvian Embassy.'),
(gen_random_uuid(), 'russia', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Russian passport holders enjoy visa-free access to Peru under bilateral agreement.'),
(gen_random_uuid(), 'nigeria', 'peru', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Peruvian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Nigerian passport holders require a visa for Peru.'),
(gen_random_uuid(), 'south-africa', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'South African passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'malaysia', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'turkey', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Turkish passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'egypt', 'peru', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Peruvian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Egyptian passport holders require a visa for Peru.'),
(gen_random_uuid(), 'indonesia', 'peru', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Peruvian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Indonesian passport holders require a visa for Peru.'),
(gen_random_uuid(), 'vietnam', 'peru', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Peruvian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Vietnamese passport holders require a visa for Peru.'),
(gen_random_uuid(), 'philippines', 'peru', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Peruvian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Filipino passport holders require a visa for Peru.'),
(gen_random_uuid(), 'qatar', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'united-arab-emirates', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'UAE passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'singapore', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Singaporean passport holders enjoy visa-free access to Peru.'),
(gen_random_uuid(), 'new-zealand', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'New Zealand passport holders enjoy visa-free access to Peru.'),

-- =====================================================
-- MOROCCO as destination
-- =====================================================
(gen_random_uuid(), 'united-states', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'US passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'united-kingdom', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'UK passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'canada', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Canadian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'australia', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Australian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'japan', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Japanese passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'south-korea', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'South Korean passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'brazil', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Brazilian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'india', 'morocco', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Moroccan Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Indian passport holders require a visa for Morocco. Apply at Moroccan Embassy. Processing 5-7 business days.'),
(gen_random_uuid(), 'china', 'morocco', 'visa_free', NULL, 30, NULL, '30 days visa-free under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Chinese passport holders enjoy visa-free access to Morocco under bilateral agreement.'),
(gen_random_uuid(), 'russia', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Russian passport holders enjoy visa-free access to Morocco under bilateral agreement.'),
(gen_random_uuid(), 'nigeria', 'morocco', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Moroccan Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Nigerian passport holders require a visa for Morocco. Apply at Moroccan Embassy.'),
(gen_random_uuid(), 'south-africa', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'South African passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'turkey', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Turkish passport holders enjoy visa-free access to Morocco. Morocco and Turkey have strong bilateral ties.'),
(gen_random_uuid(), 'malaysia', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Malaysian passport holders enjoy visa-free access to Morocco. Both Muslim-majority countries with strong ties.'),
(gen_random_uuid(), 'indonesia', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Indonesian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'singapore', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Singaporean passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'qatar', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry under Arab League agreements.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Qatari passport holders enjoy visa-free access to Morocco under Arab League agreements.'),
(gen_random_uuid(), 'united-arab-emirates', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry under bilateral agreement.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'UAE passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'new-zealand', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'New Zealand passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'argentina', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Argentine passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'chile', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Chilean passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'colombia', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Colombian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'thailand', 'morocco', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Moroccan Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Thai passport holders require a visa for Morocco.'),
(gen_random_uuid(), 'philippines', 'morocco', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Moroccan Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Filipino passport holders require a visa for Morocco.'),
(gen_random_uuid(), 'vietnam', 'morocco', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Moroccan Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Vietnamese passport holders require a visa for Morocco.')

ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
