/*
  # Add Ukraine Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Ukrainian passport holders traveling to all 51 active destinations.

  ## Ukraine Passport Profile
  - Mid-tier passport with ~140 visa-free destinations
  - NOT EU/Schengen member
  - EU has granted temporary protection for Ukrainian refugees (different from tourist visa)
  - Visa-free access to EU/Schengen under Ukraine-EU visa liberalization (2017)
  - Subject to 90/180 Schengen rule

  ## Key Notes
  - Active armed conflict since 2022 - many Ukrainians displaced
  - EU visa-free since 2017 (biometric passport required)
  - Some destinations have special arrangements given conflict situation
  - Men 18-60 may face military conscription restrictions on leaving Ukraine

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
-- EU/Schengen - visa-free 90/180 (not unlimited - Ukraine not EU)
(gen_random_uuid(), 'ukraine', 'austria', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period (combined across all Schengen countries). Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.bmeia.gv.at', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Austria under EU-Ukraine visa liberalization agreement (2017). Biometric passport required. Insurance strongly recommended given healthcare costs.'),
(gen_random_uuid(), 'ukraine', 'belgium', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://dofi.ibz.be', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Belgium. Biometric passport required. EU temporary protection may apply for those displaced by conflict.'),
(gen_random_uuid(), 'ukraine', 'croatia', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://mup.gov.hr', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Croatia. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'czech-republic', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.mvcr.cz', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Czech Republic. Large Ukrainian community in Czech Republic due to conflict.'),
(gen_random_uuid(), 'ukraine', 'denmark', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.nyidanmark.dk', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Denmark. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'finland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://migri.fi', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Finland. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'france', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://france-visas.gouv.fr', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to France. Large Ukrainian community in France. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'germany', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.bmi.bund.de', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Germany. Largest Ukrainian diaspora in EU in Germany. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'greece', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.ypes.gr', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Greece. Popular tourist destination. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'hungary', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.kormany.hu', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Hungary. Hungary shares border with Ukraine. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'ireland', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. Ireland not Schengen so separate allowance.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.irishimmigration.ie', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Ireland. Biometric passport required. Separate from Schengen quota.'),
(gen_random_uuid(), 'ukraine', 'italy', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.interno.gov.it', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Italy. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'netherlands', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://ind.nl', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Netherlands. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'norway', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.udi.no', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Norway. Norway has accepted many Ukrainian refugees. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'poland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Poland. Poland hosts the largest Ukrainian diaspora. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'portugal', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.sef.pt', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Portugal. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'romania', 'visa_free', NULL, 90, 180, '90 days within 180-day period. Romania is Schengen member.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Romania. Romania shares border with Ukraine. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'spain', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.interior.gob.es', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Spain. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'sweden', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.migrationsverket.se', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Sweden. Biometric passport required.'),
(gen_random_uuid(), 'ukraine', 'switzerland', 'visa_free', NULL, 90, 180, '90 days within 180-day Schengen period. Biometric passport required.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'required', 'https://www.sem.admin.ch', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Switzerland. Biometric passport required.'),
-- UK - visa-free
(gen_random_uuid(), 'ukraine', 'united-kingdom', 'visa_free', NULL, 180, NULL, 'Up to 6 months per visit. Special Ukraine Family Scheme and Homes for Ukraine also available.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'may_be_requested', 'https://www.gov.uk/visit-uk', '2026-02-24', 'Ukrainian passport holders can visit UK visa-free for up to 6 months. Additional Ukraine-specific schemes available for those displaced by conflict.'),
-- Americas - mostly visa-required or limited
(gen_random_uuid(), 'ukraine', 'argentina', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Argentina.'),
(gen_random_uuid(), 'ukraine', 'brazil', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Brazil.'),
(gen_random_uuid(), 'ukraine', 'chile', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Chile.'),
(gen_random_uuid(), 'ukraine', 'colombia', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Colombia.'),
(gen_random_uuid(), 'ukraine', 'mexico', 'visa_free', NULL, 180, NULL, 'Up to 180 days. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Mexico.'),
(gen_random_uuid(), 'ukraine', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Peru.'),
-- Visa-required key destinations
(gen_random_uuid(), 'ukraine', 'australia', 'evisa', 'eVisitor', 90, NULL, '90 days per visit within 12-month validity.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651', '2026-02-24', 'Ukrainian passport holders eligible for free eVisitor visa (subclass 651). Apply online before travel.'),
(gen_random_uuid(), 'ukraine', 'canada', 'visa_required', 'Visa or CUAET', 180, NULL, 'Visa required for most. Canada-Ukraine Emergency Travel Authorization (CUAET) available for those displaced by conflict.', NULL, 'valid_for_stay', 'may_be_requested', 'required', 'may_be_requested', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/ukraine-measures.html', '2026-02-24', 'Standard tourist visa required. Special CUAET program allows Ukrainians displaced by the Russian invasion to live/work in Canada for up to 3 years. Apply online through IRCC.'),
(gen_random_uuid(), 'ukraine', 'new-zealand', 'evisa', 'NZeTA', 90, NULL, '90 days per visit within 18-month validity.', 3, '3_months_beyond_departure', 'required', 'required', 'may_be_requested', 'https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/nzeta', '2026-02-24', 'NZeTA required before travel. NZD $17 via app. IVL of NZD $35 also required.'),
(gen_random_uuid(), 'ukraine', 'united-states', 'visa_required', NULL, NULL, NULL, 'Visa required (B-1/B-2 tourist/business). Ukraine is not in Visa Waiver Program.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html', '2026-02-24', 'Ukrainian passport holders require a B-1/B-2 visitor visa. Apply at US Embassy/Consulate. Uniting for Ukraine program available for those with US sponsors. Extensive documentation required.'),
-- Asia
(gen_random_uuid(), 'ukraine', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Ukrainian passport holders must obtain eVisa before travel. Apply at least 4 days before.'),
(gen_random_uuid(), 'ukraine', 'japan', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Japan under bilateral agreement.'),
(gen_random_uuid(), 'ukraine', 'malaysia', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Malaysia.'),
(gen_random_uuid(), 'ukraine', 'singapore', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Singapore.'),
(gen_random_uuid(), 'ukraine', 'south-korea', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.k-eta.go.kr', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to South Korea. K-ETA recommended for smoother entry.'),
(gen_random_uuid(), 'ukraine', 'thailand', 'visa_free', NULL, 60, NULL, '60 days visa exemption. Extendable once for 30 days.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Ukrainian passport holders enjoy 60-day visa-free entry. Thailand has been a destination for Ukrainians displaced by conflict.'),
(gen_random_uuid(), 'ukraine', 'vietnam', 'evisa', 'eVisa', 90, NULL, '90 days single or multiple entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Ukrainian passport holders can obtain eVisa (USD $25) valid for 90 days.'),
(gen_random_uuid(), 'ukraine', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable through Bureau of Immigration.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Ukrainian passport holders receive 30-day visa-free entry.'),
(gen_random_uuid(), 'ukraine', 'china', 'visa_required', NULL, NULL, NULL, 'Visa required. Tourist (L) visa typically 30-90 days.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China requires visa for Ukrainian passport holders. Apply through Chinese Visa Application Service Center.'),
-- Middle East / Africa
(gen_random_uuid(), 'ukraine', 'egypt', 'visa_on_arrival', 'VOA or eVisa', 30, NULL, '30 days single/multiple entry.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Visa on arrival (USD $25) or eVisa online (USD $25). eVisa recommended to avoid queues.'),
(gen_random_uuid(), 'ukraine', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available at major airports. Single entry, tourist only.'),
(gen_random_uuid(), 'ukraine', 'israel', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Israel. Large Ukrainian-Jewish community. Security screening at entry.'),
(gen_random_uuid(), 'ukraine', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'ukraine', 'nigeria', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply at Nigerian Embassy/Consulate.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://portal.immigration.gov.ng', '2026-02-24', 'Nigerian visa required for Ukrainian passport holders. Apply in advance. Yellow fever certificate mandatory.'),
(gen_random_uuid(), 'ukraine', 'qatar', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa waiver granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access under Qatar''s visa waiver program.'),
(gen_random_uuid(), 'ukraine', 'russia', 'restricted', NULL, NULL, NULL, 'Entry not permitted/extremely restricted due to active armed conflict. No diplomatic relations.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://mfa.gov.ua', '2026-02-24', 'Russia is at war with Ukraine. Ukrainian citizens cannot safely enter Russia. No consular services available. The Ukrainian government prohibits most travel to Russia.'),
(gen_random_uuid(), 'ukraine', 'saudi-arabia', 'visa_required', NULL, NULL, NULL, 'Visa required. Apply through Saudi embassy or official channels.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visa.visitsaudi.com', '2026-02-24', 'Saudi Arabia requires visa for Ukrainian passport holders. Tourist eVisa may be available through official channels. Check current requirements.'),
(gen_random_uuid(), 'ukraine', 'south-africa', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access to South Africa.'),
(gen_random_uuid(), 'ukraine', 'united-arab-emirates', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'Ukrainian passport holders enjoy visa-free access. UAE has been welcoming of Ukrainians displaced by conflict.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
