/*
  # Add Norway Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Norwegian passport holders traveling to all 51 active destinations.

  ## Norway Passport Profile
  - Top 3 most powerful passport globally
  - EEA/Schengen member (not EU): full Schengen access, freedom of movement in EEA
  - Nordic Passport Union member
  - Visa-free or ETA access to 190+ destinations

  ## Key Note
  Norway is NOT an EU member but IS a Schengen Area member and EEA member.
  Norwegian citizens have full freedom of movement within EEA/Schengen.

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
(gen_random_uuid(), 'norway', 'austria', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen member; Austria is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.bmeia.gv.at', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Austria under EEA agreement. National ID card or passport accepted.'),
(gen_random_uuid(), 'norway', 'belgium', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen member; Belgium is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://dofi.ibz.be', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Belgium under EEA agreement.'),
(gen_random_uuid(), 'norway', 'croatia', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Croatia is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://mup.gov.hr', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Croatia under EEA agreement.'),
(gen_random_uuid(), 'norway', 'czech-republic', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Czech Republic is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.mvcr.cz', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Czech Republic under EEA agreement.'),
(gen_random_uuid(), 'norway', 'denmark', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Nordic Passport Union and EEA/Schengen - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Norwegian citizens have unrestricted access to Denmark. Nordic Passport Union allows seamless travel.'),
(gen_random_uuid(), 'norway', 'finland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Nordic Passport Union and EEA/Schengen - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Norwegian citizens have unrestricted access to Finland. Nordic Passport Union allows seamless travel.'),
(gen_random_uuid(), 'norway', 'france', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; France is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://france-visas.gouv.fr', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in France under EEA agreement.'),
(gen_random_uuid(), 'norway', 'germany', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Germany is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.bmi.bund.de', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Germany under EEA agreement.'),
(gen_random_uuid(), 'norway', 'greece', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Greece is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.ypes.gr', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Greece under EEA agreement.'),
(gen_random_uuid(), 'norway', 'hungary', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Hungary is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.kormany.hu', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Hungary under EEA agreement.'),
(gen_random_uuid(), 'norway', 'ireland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA; Ireland is EU/EEA. Full freedom of movement under EEA.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Ireland under EEA agreement.'),
(gen_random_uuid(), 'norway', 'italy', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Italy is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.interno.gov.it', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Italy under EEA agreement.'),
(gen_random_uuid(), 'norway', 'netherlands', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Netherlands is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://ind.nl', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Netherlands under EEA agreement.'),
(gen_random_uuid(), 'norway', 'poland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Poland is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Poland under EEA agreement.'),
(gen_random_uuid(), 'norway', 'portugal', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Portugal is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.sef.pt', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Portugal under EEA agreement.'),
(gen_random_uuid(), 'norway', 'romania', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA; Romania is EU/Schengen. Full freedom of movement under EEA.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.politiadefrontiera.ro', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Romania under EEA agreement.'),
(gen_random_uuid(), 'norway', 'spain', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Norway is EEA/Schengen; Spain is EU/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.interior.gob.es', '2026-02-24', 'Norwegian citizens have full right to enter, reside, and work in Spain under EEA agreement.'),
(gen_random_uuid(), 'norway', 'sweden', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Nordic Passport Union and EEA/Schengen - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Norwegian citizens have unrestricted access to Sweden. Nordic Passport Union allows seamless travel.'),
(gen_random_uuid(), 'norway', 'switzerland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Both Norway and Switzerland are Schengen associates with bilateral agreements.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.sem.admin.ch', '2026-02-24', 'Norwegian citizens have unrestricted access to Switzerland through EEA/Schengen agreements.'),
(gen_random_uuid(), 'norway', 'argentina', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Extendable through Dirección Nacional de Migraciones.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Argentina.'),
(gen_random_uuid(), 'norway', 'brazil', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Extendable once for additional 90 days through Polícia Federal.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Brazil. Yellow fever vaccination may be required from endemic areas.'),
(gen_random_uuid(), 'norway', 'chile', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Chile.'),
(gen_random_uuid(), 'norway', 'colombia', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Extension possible through Migración Colombia.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Colombia.'),
(gen_random_uuid(), 'norway', 'israel', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Entry card issued on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Israel. Security screening at entry is thorough.'),
(gen_random_uuid(), 'norway', 'japan', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. Cannot engage in paid activities.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Norwegian passport holders enjoy visa-free access under bilateral agreement.'),
(gen_random_uuid(), 'norway', 'malaysia', 'visa_free', NULL, 90, NULL, '90 days per entry. Extendable at immigration department.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Malaysia for up to 90 days.'),
(gen_random_uuid(), 'norway', 'mexico', 'visa_free', NULL, 180, NULL, 'Up to 180 days. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Norwegian passport holders enjoy visa-free access. FMM tourist card must be retained and surrendered at departure.'),
(gen_random_uuid(), 'norway', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'norway', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry. Extensions possible through Superintendencia Nacional de Migraciones.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Peru. Yellow fever vaccination recommended for jungle regions.'),
(gen_random_uuid(), 'norway', 'qatar', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa waiver granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Norwegian passport holders enjoy visa-free access under Qatar''s visa waiver program.'),
(gen_random_uuid(), 'norway', 'singapore', 'visa_free', NULL, 90, NULL, '90 days per entry. Entry stamp issued on arrival.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Norwegian passport holders enjoy visa-free access to Singapore.'),
(gen_random_uuid(), 'norway', 'south-africa', 'visa_free', NULL, 90, NULL, '90 days per calendar year. Visitor''s visa issued at port of entry.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'Norwegian passport holders enjoy visa-free access. Must have at least 2 blank pages in passport.'),
(gen_random_uuid(), 'norway', 'south-korea', 'visa_free', NULL, 90, NULL, '90 days for tourism/business. K-ETA electronic authorization recommended.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.k-eta.go.kr', '2026-02-24', 'Norwegian passport holders enjoy visa-free access. K-ETA (KRW 10,000) recommended for smoother entry.'),
(gen_random_uuid(), 'norway', 'thailand', 'visa_free', NULL, 60, NULL, '60 days visa exemption. Extendable once for 30 days at immigration office.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Norwegian passport holders enjoy 60-day visa-free entry (extended from 30 days in 2024).'),
(gen_random_uuid(), 'norway', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Norwegian passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Check official advisories before travel.'),
(gen_random_uuid(), 'norway', 'united-arab-emirates', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'Norwegian passport holders enjoy visa-free access. Major hub for business and tourism.'),
(gen_random_uuid(), 'norway', 'australia', 'evisa', 'eVisitor', 90, NULL, '90 days per visit within 12-month validity. Multiple entries permitted.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651', '2026-02-24', 'Norwegian passport holders eligible for free eVisitor visa (subclass 651). Apply online before travel.'),
(gen_random_uuid(), 'norway', 'canada', 'evisa', 'eTA', 180, NULL, 'Up to 6 months per entry. Immigration officer determines duration at port of entry.', NULL, 'valid_for_stay', 'may_be_requested', 'required', 'may_be_requested', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html', '2026-02-24', 'eTA required for Norwegian citizens arriving by air. CAD $7 fee, valid 5 years or until passport expires.'),
(gen_random_uuid(), 'norway', 'new-zealand', 'evisa', 'NZeTA', 90, NULL, '90 days per visit within 18-month validity. Multiple entries permitted.', 3, '3_months_beyond_departure', 'required', 'required', 'may_be_requested', 'https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/nzeta', '2026-02-24', 'NZeTA required before travel. NZD $17 via app or NZD $23 via website. IVL of NZD $35 also required.'),
(gen_random_uuid(), 'norway', 'united-kingdom', 'evisa', 'ETA', 180, NULL, 'Up to 6 months per visit. Multiple entries within 2-year ETA validity.', NULL, 'valid_for_stay', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.uk/guidance/apply-for-an-electronic-travel-authorisation-eta', '2026-02-24', 'UK ETA mandatory from January 2025. £10 fee, valid 2 years. Apply online before travel.'),
(gen_random_uuid(), 'norway', 'united-states', 'evisa', 'ESTA', 90, NULL, '90 days for tourism/business under Visa Waiver Program. No extensions permitted.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://esta.cbp.dhs.gov', '2026-02-24', 'ESTA required under Visa Waiver Program. USD $21 fee, valid 2 years. Biometric passport required.'),
(gen_random_uuid(), 'norway', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days. eBusiness: up to 180 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Norwegian passport holders must obtain eVisa before travel. Apply at least 4 days before.'),
(gen_random_uuid(), 'norway', 'nigeria', 'evisa', 'eVisa on Arrival', 90, NULL, '90 days tourist/business visa. Single or multiple entry.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://portal.immigration.gov.ng', '2026-02-24', 'Norwegian passport holders must obtain eVisa before travel. USD $160 fee. Yellow fever vaccination certificate mandatory.'),
(gen_random_uuid(), 'norway', 'russia', 'evisa', 'eVisa', 16, NULL, 'eVisa: 16 days for specific regions. Single entry only.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://electronic-visa.kdmid.ru', '2026-02-24', 'eVisa for select regions. Traditional visa required elsewhere. Travel advisory in place. Check Norwegian government warnings.'),
(gen_random_uuid(), 'norway', 'saudi-arabia', 'evisa', 'eVisa', 90, 180, '90 days per visit, up to 180 days per year. Multiple entry.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visa.visitsaudi.com', '2026-02-24', 'Tourist eVisa available. SAR 300 + insurance fee. Respect local laws and dress code.'),
(gen_random_uuid(), 'norway', 'egypt', 'visa_on_arrival', 'VOA or eVisa', 30, NULL, '30 days single/multiple entry. Extensions available through Mogamma in Cairo.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Visa on arrival (USD $25) or eVisa online (USD $25). eVisa recommended to avoid queues.'),
(gen_random_uuid(), 'norway', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days. Total maximum 60 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available at major airports and seaports. Single entry, tourist only.'),
(gen_random_uuid(), 'norway', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable up to 36 months total.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Norwegian passport holders receive 30-day visa-free entry. Extensions available through Bureau of Immigration.'),
(gen_random_uuid(), 'norway', 'vietnam', 'evisa', 'eVisa', 90, NULL, '90 days single or multiple entry. Extendable within Vietnam.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Norwegian passport holders can obtain eVisa (USD $25) valid for 90 days. Apply online before travel.'),
(gen_random_uuid(), 'norway', 'china', 'visa_required', NULL, NULL, NULL, 'Visa required. Tourist (L) visa typically 30-90 days. Transit exemptions in select cities.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China requires visa for Norwegian passport holders. Apply through Chinese Visa Application Service Center.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
