/*
  # Add Missing Passport Countries

  1. Changes
    - Inserts 82 countries into the passports table that currently exist as destinations but not as passports
    - All new passports are set to is_active = true
    - Includes Australia and many other major countries
  
  2. Countries Added
    - Algeria, Angola, Argentina, Armenia, Australia, Azerbaijan, Bahamas, Bahrain, Bangladesh, Barbados, Belgium, Bolivia, Brazil, Bulgaria, Cambodia, Chile, Colombia, Costa Rica, Croatia, Cuba, Cyprus, Czech Republic, Denmark, Dominican Republic, Ecuador, Egypt, Estonia, Ethiopia, Finland, Georgia, Ghana, Hungary, Iceland, India, Indonesia, Ireland, Israel, Jamaica, Jordan, Kazakhstan, Kenya, Kuwait, Laos, Latvia, Lithuania, Luxembourg, Maldives, Malta, Mongolia, Morocco, Myanmar, Nepal, New Zealand, Nigeria, Norway, Oman, Pakistan, Panama, Paraguay, Peru, Philippines, Poland, Qatar, Romania, Serbia, Singapore, Slovakia, Slovenia, South Africa, South Korea, Sri Lanka, Sweden, Switzerland, Tanzania, Tunisia, Ukraine, Uruguay, Uzbekistan, Vietnam, Zimbabwe
*/

INSERT INTO passports (slug, name, is_active) VALUES
  ('algeria', 'Algeria', true),
  ('angola', 'Angola', true),
  ('argentina', 'Argentina', true),
  ('armenia', 'Armenia', true),
  ('australia', 'Australia', true),
  ('azerbaijan', 'Azerbaijan', true),
  ('bahamas', 'Bahamas', true),
  ('bahrain', 'Bahrain', true),
  ('bangladesh', 'Bangladesh', true),
  ('barbados', 'Barbados', true),
  ('belgium', 'Belgium', true),
  ('bolivia', 'Bolivia', true),
  ('brazil', 'Brazil', true),
  ('bulgaria', 'Bulgaria', true),
  ('cambodia', 'Cambodia', true),
  ('chile', 'Chile', true),
  ('colombia', 'Colombia', true),
  ('costa-rica', 'Costa Rica', true),
  ('croatia', 'Croatia', true),
  ('cuba', 'Cuba', true),
  ('cyprus', 'Cyprus', true),
  ('czech-republic', 'Czech Republic', true),
  ('denmark', 'Denmark', true),
  ('dominican-republic', 'Dominican Republic', true),
  ('ecuador', 'Ecuador', true),
  ('egypt', 'Egypt', true),
  ('estonia', 'Estonia', true),
  ('ethiopia', 'Ethiopia', true),
  ('finland', 'Finland', true),
  ('georgia', 'Georgia', true),
  ('ghana', 'Ghana', true),
  ('hungary', 'Hungary', true),
  ('iceland', 'Iceland', true),
  ('india', 'India', true),
  ('indonesia', 'Indonesia', true),
  ('ireland', 'Ireland', true),
  ('israel', 'Israel', true),
  ('jamaica', 'Jamaica', true),
  ('jordan', 'Jordan', true),
  ('kazakhstan', 'Kazakhstan', true),
  ('kenya', 'Kenya', true),
  ('kuwait', 'Kuwait', true),
  ('laos', 'Laos', true),
  ('latvia', 'Latvia', true),
  ('lithuania', 'Lithuania', true),
  ('luxembourg', 'Luxembourg', true),
  ('maldives', 'Maldives', true),
  ('malta', 'Malta', true),
  ('mongolia', 'Mongolia', true),
  ('morocco', 'Morocco', true),
  ('myanmar', 'Myanmar', true),
  ('nepal', 'Nepal', true),
  ('new-zealand', 'New Zealand', true),
  ('nigeria', 'Nigeria', true),
  ('norway', 'Norway', true),
  ('oman', 'Oman', true),
  ('pakistan', 'Pakistan', true),
  ('panama', 'Panama', true),
  ('paraguay', 'Paraguay', true),
  ('peru', 'Peru', true),
  ('philippines', 'Philippines', true),
  ('poland', 'Poland', true),
  ('qatar', 'Qatar', true),
  ('romania', 'Romania', true),
  ('serbia', 'Serbia', true),
  ('singapore', 'Singapore', true),
  ('slovakia', 'Slovakia', true),
  ('slovenia', 'Slovenia', true),
  ('south-africa', 'South Africa', true),
  ('south-korea', 'South Korea', true),
  ('sri-lanka', 'Sri Lanka', true),
  ('sweden', 'Sweden', true),
  ('switzerland', 'Switzerland', true),
  ('tanzania', 'Tanzania', true),
  ('tunisia', 'Tunisia', true),
  ('ukraine', 'Ukraine', true),
  ('uruguay', 'Uruguay', true),
  ('uzbekistan', 'Uzbekistan', true),
  ('vietnam', 'Vietnam', true),
  ('zimbabwe', 'Zimbabwe', true)
ON CONFLICT (slug) DO NOTHING;
