/*
  # Add Romania Passport Visa Rules

  ## Overview
  Complete outbound visa rules for Romanian passport holders traveling to all 51 active destinations.

  ## Romania Passport Profile
  - EU member since 2007
  - Joined Schengen Area in 2024 (air/sea borders; full land border integration ongoing)
  - Visa-free access to ~175+ destinations
  - Weaker than Western EU passports for some non-EU destinations

  ## Key Notes
  - As EU member, full freedom of movement in EU/EEA
  - Schengen membership allows travel in Schengen without border checks
  - Some non-EU destinations may require visa where Western EU does not

  Data verified: 2026-02-24
*/

INSERT INTO visa_rules (id, passport_slug, destination_slug, visa_type, visa_subtype, max_stay_days, stay_window_days, stay_rule, passport_validity_months, passport_validity_requirement, return_ticket_required, sufficient_funds_required, insurance_required, official_source_url, last_verified, notes)
VALUES
-- EU/Schengen - unlimited freedom of movement
(gen_random_uuid(), 'romania', 'austria', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Austria are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.bmeia.gv.at', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Austria. EHIC provides healthcare coverage.'),
(gen_random_uuid(), 'romania', 'belgium', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Belgium are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://dofi.ibz.be', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Belgium.'),
(gen_random_uuid(), 'romania', 'croatia', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Croatia are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://mup.gov.hr', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Croatia.'),
(gen_random_uuid(), 'romania', 'czech-republic', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Czech Republic are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.mvcr.cz', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Czech Republic.'),
(gen_random_uuid(), 'romania', 'denmark', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Denmark are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.nyidanmark.dk', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Denmark.'),
(gen_random_uuid(), 'romania', 'finland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Finland are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://migri.fi', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Finland.'),
(gen_random_uuid(), 'romania', 'france', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and France are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://france-visas.gouv.fr', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in France. Large Romanian community in France.'),
(gen_random_uuid(), 'romania', 'germany', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Germany are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.bmi.bund.de', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Germany. Large Romanian diaspora in Germany.'),
(gen_random_uuid(), 'romania', 'greece', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Greece are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.ypes.gr', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Greece.'),
(gen_random_uuid(), 'romania', 'hungary', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Hungary are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.kormany.hu', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Hungary. Significant Hungarian minority in Romania.'),
(gen_random_uuid(), 'romania', 'ireland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Ireland are both EU members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.irishimmigration.ie', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Ireland. Large Romanian community in Ireland.'),
(gen_random_uuid(), 'romania', 'italy', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Italy are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.interno.gov.it', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Italy. Largest Romanian diaspora community in Italy.'),
(gen_random_uuid(), 'romania', 'netherlands', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Netherlands are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://ind.nl', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Netherlands.'),
(gen_random_uuid(), 'romania', 'norway', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania is EU/Schengen; Norway is EEA/Schengen. Full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.udi.no', '2026-02-24', 'Romanian citizens have full right to enter, reside, and work in Norway under EEA agreement.'),
(gen_random_uuid(), 'romania', 'poland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Poland are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.gov.pl/web/mswia', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Poland.'),
(gen_random_uuid(), 'romania', 'portugal', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Portugal are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.sef.pt', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Portugal.'),
(gen_random_uuid(), 'romania', 'spain', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Spain are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.interior.gob.es', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Spain. Large Romanian diaspora in Spain.'),
(gen_random_uuid(), 'romania', 'sweden', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania and Sweden are both EU/Schengen members - full freedom of movement.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.migrationsverket.se', '2026-02-24', 'Romanian citizens have unrestricted right to enter, reside, and work in Sweden.'),
(gen_random_uuid(), 'romania', 'switzerland', 'visa_free', NULL, NULL, NULL, 'Unlimited stay. Romania is EU/Schengen; Switzerland is Schengen associate with bilateral agreements.', NULL, 'valid_for_stay', 'not_typically_requested', 'not_typically_requested', 'not_typically_requested', 'https://www.sem.admin.ch', '2026-02-24', 'Romanian citizens have full right to enter, reside, and work in Switzerland under EEA agreement.'),
-- UK - visa-free post-Brexit
(gen_random_uuid(), 'romania', 'united-kingdom', 'visa_free', NULL, 180, NULL, 'Up to 6 months per visit for tourism/business. Standard visitor rules apply.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.uk/visit-uk', '2026-02-24', 'Romanian citizens can visit UK visa-free for up to 6 months. Cannot work or study without permission. Large Romanian community in UK.'),
-- Americas
(gen_random_uuid(), 'romania', 'argentina', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.argentina.gob.ar/interior/migraciones', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Argentina.'),
(gen_random_uuid(), 'romania', 'brazil', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.br/mre/pt-br', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Brazil.'),
(gen_random_uuid(), 'romania', 'chile', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.extranjeria.gob.cl', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Chile.'),
(gen_random_uuid(), 'romania', 'colombia', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migracioncolombia.gov.co', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Colombia.'),
(gen_random_uuid(), 'romania', 'mexico', 'visa_free', NULL, 180, NULL, 'Up to 180 days. FMM tourist card issued at entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.inm.gob.mx', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Mexico.'),
(gen_random_uuid(), 'romania', 'peru', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.migraciones.gob.pe', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Peru. Yellow fever vaccination recommended for jungle regions.'),
-- ETAs
(gen_random_uuid(), 'romania', 'australia', 'evisa', 'eVisitor', 90, NULL, '90 days per visit within 12-month validity. Multiple entries permitted.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651', '2026-02-24', 'Romanian passport holders eligible for free eVisitor visa (subclass 651). Apply online before travel.'),
(gen_random_uuid(), 'romania', 'canada', 'evisa', 'eTA', 180, NULL, 'Up to 6 months per entry.', NULL, 'valid_for_stay', 'may_be_requested', 'required', 'may_be_requested', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html', '2026-02-24', 'eTA required for Romanian citizens arriving by air. CAD $7 fee, valid 5 years.'),
(gen_random_uuid(), 'romania', 'new-zealand', 'evisa', 'NZeTA', 90, NULL, '90 days per visit within 18-month validity.', 3, '3_months_beyond_departure', 'required', 'required', 'may_be_requested', 'https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/nzeta', '2026-02-24', 'NZeTA required before travel. NZD $17 via app. IVL of NZD $35 also required.'),
(gen_random_uuid(), 'romania', 'united-states', 'evisa', 'ESTA', 90, NULL, '90 days for tourism/business under Visa Waiver Program.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://esta.cbp.dhs.gov', '2026-02-24', 'ESTA required under Visa Waiver Program. USD $21 fee. Romania joined VWP in 2023.'),
-- eVisas
(gen_random_uuid(), 'romania', 'india', 'evisa', 'eTourist', 60, NULL, 'eTourist Visa: 30/60 days. eBusiness: up to 180 days.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://indianvisaonline.gov.in', '2026-02-24', 'Romanian passport holders must obtain eVisa before travel. Apply at least 4 days before.'),
(gen_random_uuid(), 'romania', 'nigeria', 'evisa', 'eVisa on Arrival', 90, NULL, '90 days tourist/business visa.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://portal.immigration.gov.ng', '2026-02-24', 'Romanian passport holders must obtain eVisa before travel. USD $160 fee. Yellow fever certificate mandatory.'),
(gen_random_uuid(), 'romania', 'russia', 'visa_required', NULL, NULL, NULL, 'Visa required. Diplomatic relations affected by Russia-Ukraine conflict.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://electronic-visa.kdmid.ru', '2026-02-24', 'Romania does not have bilateral visa-free agreement with Russia. Tourist visa required. Travel advisory strongly in place due to geopolitical situation.'),
(gen_random_uuid(), 'romania', 'saudi-arabia', 'evisa', 'eVisa', 90, 180, '90 days per visit, up to 180 days per year. Multiple entry.', 6, '6_months_beyond_entry', 'required', 'required', 'required', 'https://visa.visitsaudi.com', '2026-02-24', 'Tourist eVisa available. SAR 300 + insurance fee. Respect local laws and dress code.'),
-- Visa on Arrival
(gen_random_uuid(), 'romania', 'egypt', 'visa_on_arrival', 'VOA or eVisa', 30, NULL, '30 days single/multiple entry.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://visa2egypt.gov.eg', '2026-02-24', 'Visa on arrival (USD $25) or eVisa online (USD $25). eVisa recommended to avoid queues.'),
(gen_random_uuid(), 'romania', 'indonesia', 'visa_on_arrival', NULL, 30, NULL, '30 days, extendable once for additional 30 days.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.imigrasi.go.id', '2026-02-24', 'Visa on Arrival (IDR 500,000) available at major airports. Single entry, tourist only.'),
-- Visa-free other
(gen_random_uuid(), 'romania', 'israel', 'visa_free', NULL, 90, 180, '90 days per 180-day period.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.gov.il/en/departments/topics/visa/govil-landing-page', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Israel. Security screening at entry is thorough.'),
(gen_random_uuid(), 'romania', 'japan', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', NULL, 'valid_for_stay', 'required', 'required', 'not_typically_requested', 'https://www.mofa.go.jp/j_info/visit/visa/index.html', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Japan under bilateral agreement.'),
(gen_random_uuid(), 'romania', 'malaysia', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.imi.gov.my', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Malaysia for up to 90 days.'),
(gen_random_uuid(), 'romania', 'morocco', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.mtpnet.gov.ma', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Morocco.'),
(gen_random_uuid(), 'romania', 'philippines', 'visa_free', NULL, 30, NULL, '30 days visa-free on arrival. Extendable through Bureau of Immigration.', 6, '6_months_beyond_entry', 'required', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.gov.ph', '2026-02-24', 'Romanian passport holders receive 30-day visa-free entry. Extensions available.'),
(gen_random_uuid(), 'romania', 'qatar', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa waiver granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://portal.moi.gov.qa', '2026-02-24', 'Romanian passport holders enjoy visa-free access under Qatar''s visa waiver program.'),
(gen_random_uuid(), 'romania', 'singapore', 'visa_free', NULL, 90, NULL, '90 days per entry.', 6, '6_months_beyond_entry', 'required', 'required', 'not_typically_requested', 'https://www.ica.gov.sg', '2026-02-24', 'Romanian passport holders enjoy visa-free access to Singapore.'),
(gen_random_uuid(), 'romania', 'south-africa', 'visa_free', NULL, 90, NULL, '90 days per calendar year.', 6, '6_months_beyond_departure', 'required', 'required', 'not_typically_requested', 'http://www.dha.gov.za', '2026-02-24', 'Romanian passport holders enjoy visa-free access to South Africa.'),
(gen_random_uuid(), 'romania', 'south-korea', 'visa_free', NULL, 90, NULL, '90 days for tourism/business.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.k-eta.go.kr', '2026-02-24', 'Romanian passport holders enjoy visa-free access. K-ETA recommended for smoother entry.'),
(gen_random_uuid(), 'romania', 'thailand', 'visa_free', NULL, 60, NULL, '60 days visa exemption. Extendable once for 30 days.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://www.immigration.go.th', '2026-02-24', 'Romanian passport holders enjoy 60-day visa-free entry (extended from 30 days in 2024).'),
(gen_random_uuid(), 'romania', 'ukraine', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Active conflict - check travel advisories.', 6, '6_months_beyond_entry', 'not_typically_requested', 'not_typically_requested', 'required', 'https://visitukraine.today', '2026-02-24', 'Romanian passport holders enjoy visa-free access. IMPORTANT: Active armed conflict. Romania shares a border with Ukraine - check official advisories.'),
(gen_random_uuid(), 'romania', 'united-arab-emirates', 'visa_free', NULL, 90, 180, '90 days per 180-day period. Visa granted on arrival.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://u.ae/en/information-and-services/visa-and-emirates-id', '2026-02-24', 'Romanian passport holders enjoy visa-free access.'),
(gen_random_uuid(), 'romania', 'vietnam', 'evisa', 'eVisa', 90, NULL, '90 days single or multiple entry.', 6, '6_months_beyond_entry', 'may_be_requested', 'may_be_requested', 'not_typically_requested', 'https://evisa.xuatnhapcanh.gov.vn', '2026-02-24', 'Romanian passport holders can obtain eVisa (USD $25) valid for 90 days.'),
(gen_random_uuid(), 'romania', 'china', 'visa_required', NULL, NULL, NULL, 'Visa required. Tourist (L) visa typically 30-90 days.', 6, '6_months_beyond_entry', 'required', 'required', 'may_be_requested', 'https://www.visaforchina.cn', '2026-02-24', 'China requires visa for Romanian passport holders. Apply through Chinese Visa Application Service Center.')
ON CONFLICT ON CONSTRAINT visa_rules_passport_destination_subtype_key DO NOTHING;
