/*
  # Update Austria Passport Complete Visa Requirements

  1. Updates for Austria Passport Holders
    - Fix all destination visa requirements with accurate data
    - Add EU Freedom of Movement for all EU destinations
    - Add Brazil visa requirement (required since April 10, 2025)
    - Add Australia eVisitor requirement
    - Add Canada eTA requirement
    - Add China temporary visa-free arrangement
    - Add New Zealand NZeTA requirement
    - Add Russia eVisa requirement
    - Add Thailand 60-day visa-free stay
    - Add Turkey eVisa requirement
    - Add UK ETA requirement (from April 2, 2025 - post-Brexit)
    - Add Vietnam eVisa requirement
    - Set last_verified to 2026-02-19

  2. Key Features for Austria
    - EU Freedom of Movement: Belgium, Croatia, Czech Republic, France, Germany, Greece, Hungary, Italy, Netherlands, Poland, Portugal, Spain (indefinite residence rights)
    - Switzerland: AFMP bilateral agreement (EU freedom of movement equivalent)
    - Brazil: VISA REQUIRED since April 10, 2025
    - Australia: eVisitor (free) required
    - Canada: eTA required
    - UK: ETA required from April 2, 2025 (post-Brexit change)
    - USA: ESTA under VWP
    - Note: Austria does not permit dual citizenship

  3. Affected Destinations
    All 42 destinations for Austria passport holders
*/

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral arrangement for tourism or short business visits. EU passport holders including Austrians benefit from visa-free access. 90 days within any 180-day period. Extendable once for additional 90 days at Argentine immigration authority (DNM). Passport required — national ID card not accepted. Return ticket and proof of funds may be requested. Yellow fever certificate if arriving from endemic country. As EU citizen, consular support from any EU mission available.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'argentina';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisitor (free)', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'eVisitor visa (subclass 651) REQUIRED before boarding — free of charge. Apply online at immi.homeaffairs.gov.au. Usually approved within 24-72 hours. Valid 12 months from grant date, multiple entries. Up to 3 months per visit within 12-month period. ETA (subclass 601) also available for AUD 20 fee. Proof of funds and return ticket required. Fingerprinting and biometric checks on arrival. Strict biosecurity — declare all food, plant, animal products. Working Holiday Visa (subclass 417) available for ages 18-30. Must use same passport at airport as used for eVisitor application.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'australia';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. No visa, passport control, or advance authorization required. Entry and residence guaranteed under EU law. Austrians can reside in Belgium indefinitely; registration with local commune required for stays beyond 3 months. Austrian national ID card accepted as travel document — no passport necessary. No border checks within Schengen Area. Full EU treaty rights including healthcare, education, voting in local and European Parliament elections.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'belgium';

UPDATE visa_rules SET visa_type = 'visa_required', visa_subtype = 'Tourist visa (VIVIS)', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'VISA REQUIRED as of April 10, 2025. Brazil reinstated visa requirements for EU passport holders including Austria as reciprocity measure. Tourist visa must be obtained before travel via Brazilian government consular portal or at Brazilian Embassy in Vienna. Typically 90 days per visit. Passport valid 6 months beyond entry. Documents: passport, photo, travel itinerary, proof of accommodation, proof of funds. Return ticket required. Biometric fingerprinting on arrival. SIGNIFICANT CHANGE from pre-April 2025 visa-free arrangement.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'brazil';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eTA', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'eTA (Electronic Travel Authorization) MANDATORY before boarding any flight to Canada. Apply at canada.ca/eta. Fee CAD 7. Usually approved within minutes to few days. Valid 5 years or until passport expiry. Multiple entries. Up to 6 months per visit at border officer discretion. Entry by land or sea does not require eTA. Proof of funds, return ticket, ties to Austria may be requested. Biometric fingerprinting at border. Working Holiday Visa arrangement for ages 18-35. As EU citizen, consular assistance at any EU mission available if no Austrian mission accessible.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'canada';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. EU passport holders including Austrians benefit from bilateral arrangement. 90 days within any 180-day period. Passport required — national ID card not accepted. Return ticket may be requested. Proof of funds may be requested at land borders. Working Holiday visa available for ages 18-35. Entry seamless at all international airports and land borders. Note: Austria does not recognise dual citizenship — Austrians who naturalise as Chilean citizens automatically lose Austrian citizenship.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'chile';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Temporary arrangement', max_stay_days = 30, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'TEMPORARY unilateral visa-free entry policy valid until December 31, 2026. Austria explicitly listed among 48 eligible countries. 30 days per visit for tourism, business, family visits, exchange, or transit. Outside this window, standard tourist (L) or business (M) visa required. Verify arrangement extension before booking beyond Dec 2026. Passport valid for intended stay; 6 months strongly recommended. Return ticket required. Hotel booking or invitation letter recommended. Biometric fingerprinting on arrival. Digital Arrival Card must be completed. Also note: 240-hour (10-day) visa-free transit zones in major Chinese cities. Austrian Federal Ministry advises awareness of China''s broad national security laws.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'china';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business visits. 90 days within any 180-day period. Extendable once for additional 90 days at Migración Colombia. Passport required — national ID card not accepted. Return ticket may be requested. Yellow fever certificate if arriving from endemic country. Entry smooth at all international airports and land borders. As EU citizen, consular support from any EU mission available if no Austrian mission locally.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'colombia';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Croatia joined EU in 2013 and Schengen Area January 2023. No visa, passport stamp, or advance authorization required. Indefinite residence under EU law. Registration with local Croatian police required for stays exceeding 3 months. Austrian national ID card accepted — no passport necessary. No border controls within Schengen Area. Austria and Croatia share land border, making overland travel seamless. Full EU rights including healthcare and education access.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'croatia';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with Czech Foreign Police required for stays exceeding 30 days. Austrian national ID card accepted — no passport necessary. No border controls within Schengen Area. Austria and Czech Republic share land border with high daily cross-border traffic. Travel seamless — no documentation requirements beyond ID card. Strong economic and cultural ties.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'czech-republic';

UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or e-Visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa on arrival at major Egyptian international airports. E-Visa also available at visa2egypt.gov.eg, apply at least 7 days before travel. 30 days per entry. Maximum 3 entries and no more than 90 days total per calendar year. Visa fee USD 25 (payable in USD, EUR, or GBP at airport). Return ticket required. Hotel reservation required. Proof of funds required. Biometrics may be collected on arrival. E-Visa processed within 5-7 business days. Note: diplomatic and service passport holders from Austria exempt from visa requirement.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'egypt';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Both EU and Schengen Area founding members. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with French authorities (OFII) required for stays exceeding 3 months if taking up employment or establishing residence. Austrian national ID card accepted — no passport necessary. No border checks within Schengen Area. Full EU rights including social security, healthcare, public services. Tax residency rules apply if residing 183+ days per year. Voting rights in municipal and European Parliament elections.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'france';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Neighboring fellow EU member. Austria and Germany share long land border with extremely high cross-border traffic. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with Einwohnermeldeamt (residents registration office) required within 14 days of establishing primary residence. Austrian national ID card (Personalausweis) accepted — no passport necessary. Cross-border commuting extremely common. Germany is Austria''s most important bilateral partner. Same language, extensive economic, cultural, family ties. Failure to register is administrative offense under Bundesmeldegesetz.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'germany';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Fellow EU and Schengen Area member. No visa, passport stamp, or advance authorization required. Indefinite residence under EU law. Registration with local police authority (KEP) required for stays exceeding 3 months to obtain EU residence certificate. Austrian national ID card accepted — no passport necessary. No internal Schengen border controls. Greece major tourism destination for Austrians. Full EU rights including healthcare and education. Tax residency rules may apply for extended stays.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'greece';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Neighboring fellow EU and Schengen Area member. Austria and Hungary share land border with very high cross-border traffic. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with local Hungarian authorities required for stays exceeding 93 days. Austrian national ID card accepted — no passport necessary. Cross-border commuting common and entirely unrestricted. Deep historical ties (Habsburg Empire). Full EU treaty rights including voting in municipal and European Parliament elections. Failure to register after 93 days is administrative offense.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'hungary';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'e-Tourist Visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'E-Tourist Visa (e-TV) required. Apply at indianvisaonline.gov.in at least 4 days before arrival and no more than 120 days in advance. 30 days per visit. Maximum 2 e-Tourist Visas per calendar year. 1-year and 5-year e-Tourist Visas (multiple entries, 90 days per visit) also available at higher fees. Fee USD 25 for 30-day variant. Processing 72-96 hours. Must arrive via one of 32 designated airports or 5 seaports. Passport must have at least 2 blank pages. Return ticket required. Proof of funds and accommodation required. e-Tourist Visa entirely online; consular visa requires in-person biometric collection at Indian Embassy in Vienna or Consulate in Salzburg.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'india';

UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or eVisa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa on Arrival (VoA) or eVisa available. VoA (IDR 500,000, approx. USD 30) at designated airports including Bali (Ngurah Rai), Jakarta (Soekarno-Hatta), Surabaya (Juanda). eVisa also available via molina.imigrasi.go.id. 30 days per visit. Extendable once for additional 30 days at local immigration office. Passport must have at least one blank page. Return ticket required. Yellow fever certificate if arriving from endemic country. VoA payable in cash (IDR or USD) or card at immigration counter. Biometric fingerprinting on arrival. eVisa convenient pre-travel alternative. Diplomatic and service passport holders may have additional visa-free access.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'indonesia';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Fellow EU and Schengen Area founding member. Austria and Italy share land border across the Alps. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with local Anagrafe (municipal registry) required for stays exceeding 3 months. Austrian national ID card accepted — no passport necessary. Brenner Pass (Austria-Italy) one of busiest land crossings in Europe with no passport checks. Full EU rights including social services. Tax residency rules apply if residing 183+ days per year. South Tyrol region has large German-speaking Austrian-heritage community.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'italy';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business visits under bilateral agreement. 90 days per visit. Persons previously sentenced to 1+ year imprisonment not eligible and must obtain visa. Return ticket required. Proof of sufficient funds and accommodation required. Biometric fingerprinting and photograph on arrival. Departure tax (JPY 1,000) collected by airline. Working Holiday arrangement for ages 18-30. Japan Visit Web digital declaration should be completed before landing. Entry straightforward at all international airports. Biometrics enrolled at immigration counter.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'japan';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. EU passport holders including Austrians benefit from visa-free access. 90 days per visit. Passport valid at least 6 months. Return ticket may be requested. Biometric fingerprinting on arrival and departure at all international entry points. Immigration offenses including overstays treated seriously. Entry efficient at all international airports. Malaysia My Second Home (MM2H) visa available for long-term stays.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'malaysia';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free for tourism, transit, or short business stays. EU passport holders including Austrians benefit from bilateral arrangement. Up to 180 days for tourism; up to 120 days for business per calendar year. Actual duration at immigration officer discretion. Multiple Immigration Form (FMM) must be completed on arrival or in advance. FMM included in airfare for air travel; fees apply for land entry stays exceeding 7 days. Working Holiday Visa arrangement for ages 18-30. Entry smooth at all international airports and land borders. FMM must be retained and collected on departure.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'mexico';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Fellow EU and Schengen Area founding member. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with local municipality (gemeente) required for stays exceeding 4 months. Austrian national ID card accepted — no passport necessary. No border checks within Schengen Area. Full EU rights including social services. Must register with gemeente and obtain BSN (citizen service number) for long stays. Tax residency rules apply. Full healthcare and education access.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'netherlands';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'NZeTA', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'NZeTA (New Zealand Electronic Travel Authority) MANDATORY before boarding. Austrian citizens on visa waiver list. Apply online or via NZeTA app. Fee NZD 23 (mobile app) or NZD 35 (online). International Visitor Conservation and Tourism Levy (IVL) of NZD 35 also applies. Valid 2 years or until passport expiry. Up to 90 days per visit. Passport must be valid at least 3 months beyond departure. Return travel required. Proof of funds may be requested. Biometric checks at border. NZeTA typically approved within 72 hours. Must use same passport as NZeTA application. NZeTA linked electronically — no label or stamp issued.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'new-zealand';

UPDATE visa_rules SET visa_type = 'visa_required', visa_subtype = 'eVisa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa required prior to travel. Nigeria does not offer visa on arrival for Austrian or EU passport holders. eVisa most convenient option at portal.immigration.gov.ng or apply at Nigerian High Commission or Embassy. Processing typically 2-3 business days for online applications. Typically 30 days for tourist visa, extendable at Nigeria Immigration Service. Passport valid at least 6 months with at least 2 blank pages. Return ticket required. Proof of hotel booking or invitation letter required. Yellow fever vaccination certificate mandatory. Apply at least 2 weeks before travel. Biometrics collected at Lagos and Abuja airports. As EU citizen, consular support from any EU mission available if no Austrian mission accessible.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'nigeria';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism stays. EU passport holders including Austrians benefit from visa-free access. Entry granted on arrival. 30 days on arrival. Extendable at Bureau of Immigration to maximum 59 days, then further in monthly increments up to 3 years. Passport valid at least 6 months beyond departure. Return ticket required. Proof of sufficient funds and accommodation required. Yellow fever certificate if arriving from endemic country. Entry simple at all international airports. Biometric data collected on arrival. Bureau of Immigration extensions applied in person.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'philippines';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Fellow EU and Schengen Area member. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with local Polish authorities (Urząd) required for stays exceeding 3 months. Austrian national ID card accepted — no passport necessary. No border checks within Schengen Area. Full EU rights including healthcare and education. Failure to register after 3 months technically administrative violation under Polish law.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'poland';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Fellow EU and Schengen Area founding member. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with AIMA (successor to SEF) required for stays exceeding 3 months to obtain EU residence certificate. Austrian national ID card accepted — no passport necessary. No border checks within Schengen Area. Full EU rights including access to Portugal NHR (Non-Habitual Resident) tax regime for new arrivals. Portugal major destination for Austrian tourists and retirees seeking warmer climate. Tax residency rules apply for extended stays.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'portugal';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. EU passport holders including Austrians benefit from visa-free access. Free visa on arrival stamp issued at Hamad International Airport. 30 days per visit. Extendable at General Directorate of Passports. Return ticket required. Proof of hotel booking or sufficient funds required. Biometric iris scanning and fingerprinting on arrival. Entry seamless. Qatar major aviation hub and transit point for Austrians traveling to Asia and Africa.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'qatar';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'eVisa REQUIRED. Russian eVisa available online at evisa.kdmid.ru — most convenient option for EU/Schengen passport holders. Fee USD 52. Processing approximately 4 calendar days. Valid 60 days from issue; single entry. Up to 30 days per visit. Entry via any international airport permitted; land border crossings with eVisa limited to designated points. Return ticket required. Biometric data on arrival. Mandatory registration with local authorities (hotel or OVIR) within 7 business days. CRITICAL: Austrian Federal Ministry maintains elevated travel advisory due to Ukraine conflict, arbitrary detention risk, severely limited consular assistance. Direct flights Vienna-Russia suspended due to mutual airspace restrictions. Travel typically via third countries (Turkey, UAE, Serbia). Austrian citizens detained in Russia face particular legal vulnerability.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'russia';

UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or eVisa', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 6, return_ticket_required = true, insurance_required = true, sufficient_funds_required = true, notes = 'Saudi tourist visa on arrival at designated entry points or eVisa at visa.visitsaudi.com. EU passport holders including Austrians eligible (Saudi opened tourism to EU citizens in 2019). Up to 90 days per year (single or multiple visits). eVisa application up to 30 days before travel. Return ticket required. Hotel booking required. Travel insurance required (included in eVisa package). Biometric iris scanning and fingerprinting on arrival. Non-Muslim visitors prohibited from entering Mecca. eVisa valid 1 year, multiple entries. Cost approximately USD 80 (includes mandatory health insurance). Approval within minutes to few days. Austria-Saudi Arabia significant bilateral economic relationship.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'saudi-arabia';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. EU passport holders including Austrians benefit from visa-free access. 30 days per visit. Extendable at Immigration and Checkpoints Authority (ICA) before authorized stay expires. Return ticket strongly recommended. Proof of funds and accommodation may be requested. Biometric fingerprinting and photo on arrival and departure. Singapore strictly enforces immigration laws. Automated eGates available at Changi Airport. SG Arrival Card digital declaration must be completed before landing. Biometrics collected on arrival and departure.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'singapore';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 1, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free for tourism, transit, or short business stays. EU passport holders including Austrians benefit from visa-free access. 30 days per visit. Passport valid at least 1 month beyond departure with minimum 2 blank pages for stamps. Yellow fever certificate required if arriving from or transiting through endemic country. Biometric enrollment on arrival. Entry straightforward at OR Tambo International (Johannesburg) and other major ports. Travel insurance strongly recommended.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'south-africa';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'K-ETA', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'K-ETA (Korea Electronic Travel Authorization) MANDATORY before travel. Apply at k-eta.go.kr at least 72 hours before departure. Fee KRW 10,000 (approx. USD 7). Valid 3 years for multiple entries. Up to 90 days within any 12-month period. Return ticket required. Proof of funds and accommodation may be requested. Biometric fingerprinting and photo on arrival. Persons with 1+ year imprisonment not eligible. Bilateral Working Holiday arrangement. Automated eGates at Incheon and major airports for enrolled travelers. K-ETA approved within 72 hours. Must use same passport as K-ETA application.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'south-korea';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU Freedom of Movement', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'EU Freedom of Movement — unrestricted right of residence. Fellow EU and Schengen Area member. No visa, border controls, or advance authorization required. Indefinite residence under EU law. Registration with Oficina de Extranjería and Padrón Municipal required for stays exceeding 3 months to obtain EU registration certificate (NIE). Austrian national ID card accepted — no passport necessary. No border checks within Schengen Area. Spain major tourism destination for Austrians. Full EU rights. Tax residency rules apply 183+ days per year. Full healthcare and education access.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'spain';

UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'EU-Switzerland AFMP', max_stay_days = null, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free under EU-Switzerland bilateral agreements and Schengen membership. Switzerland is Schengen member with extensive bilateral agreements with EU guaranteeing freedom of movement for EU citizens including Austrians. Indefinite residence under Agreement on Free Movement of Persons (AFMP). Registration with Swiss Gemeinde (commune) required for stays exceeding 3 months. Austrian national ID card accepted — no passport necessary. No border controls between Austria and Switzerland. Austria and Switzerland neighbors with very high cross-border traffic. Both share German as primary language. Cross-border commuting extremely common (Vorarlberg-St. Gallen region). Must obtain B permit (short-term residence) or L permit (short-stay) for long stays. Switzerland maintains SEM immigration authority parallel with Schengen.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'switzerland';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 60, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism stays under bilateral arrangement. EU passport holders including Austrians benefit from visa-free access. Entry granted on arrival. 60 days per visit (INCREASED from 30 days in 2024 under Thailand tourism promotion policy). Extendable once for additional 30 days at local immigration office (THB 1,900 fee). Passport valid at least 6 months. Return ticket expected by immigration. Proof of funds (THB 20,000 per person or 40,000 per family) may be requested. Biometric fingerprinting on arrival. Thailand Digital Arrival Card (TDAC) may be required. Entry seamless at major international airports. Thailand popular long-haul destination for Austrian tourists. Extensions applied in person at local immigration offices.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'thailand';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisa', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'eVisa REQUIRED before or upon arrival. eVisa available at evisa.gov.tr — strongly preferred. Apply at least 48 hours before travel. Fee USD 60 for Austrian citizens. Valid 180 days from issue, single entry for most nationalities. 90 days within any 180-day period. Visa on arrival also available at major airports but queues can be lengthy. Passport valid at least 6 months. Return ticket not formally required but may be requested. Proof of accommodation may be requested. Biometric data collected on arrival. eVisa approval typically within minutes to few hours. Turkey popular transit and tourism destination for Austrians. Note: diplomatic and official passport holders may have separate visa-free arrangements.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'turkey';

UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Free visa on arrival stamp at any UAE port of entry. EU passport holders including Austrians benefit from visa-free access. 30 days per visit. Extendable for additional 30 days through GDRFA. Return ticket required. Proof of sufficient funds and hotel booking required. Biometric iris scanning and fingerprinting on arrival at all UAE ports. Entry seamless at Dubai International, Abu Dhabi International, and all other UAE airports. Austria-UAE bilateral trade and business ties strong with UAE Expo connections and significant Austrian business presence in Dubai. Visa extension applications online or at GDRFA offices. Biometrics enrolled on first entry.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'united-arab-emirates';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'UK ETA', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'UK Electronic Travel Authorisation (ETA) MANDATORY from April 2, 2025. POST-BREXIT CHANGE: ETA became applicable to Austrian and all EU passport holders from April 2, 2025. Prior to 2025, EU nationals could enter UK without advance authorization. Apply via UK ETA app or online at gov.uk. Fee GBP 16 (approx. €20). Valid 2 years or until passport expiry. Multiple entries. Up to 6 months per visit. IMPORTANT: Since Brexit, EU national ID cards no longer accepted for UK entry — valid passport required. Return ticket may be requested. Proof of funds and purpose of visit may be verified. Biometric checks at UK border. eGates available at major UK airports. ETA approved within hours (up to 3 business days). Must use same passport linked to ETA.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'united-kingdom';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'ESTA', max_stay_days = 90, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'ESTA (Electronic System for Travel Authorization) MANDATORY under Visa Waiver Program (VWP). Apply at esta.cbp.dhs.gov at least 72 hours before departure. Fee USD 21. Valid 2 years or until passport expiry. Up to 90 days per visit. Cannot be extended under VWP. Passport must be e-passport (biometric chip). Return ticket required. Biometric fingerprinting and photo on arrival. CRITICAL: Overstaying even 1 day permanently forfeits ESTA eligibility. Persons who traveled to Iran, Iraq, Libya, North Korea, Somalia, Sudan, Syria, or Yemen since March 1, 2011 ineligible for ESTA. IMPORTANT: Austria does not permit dual citizenship — ESTA ineligibility based on dual nationality of VWP-excluded country less common for Austrians. Austria strict prohibition on dual citizenship means Austrians who naturalise in US automatically lose Austrian passport.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'united-states';

UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisa', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'eVisa REQUIRED before travel. Apply at evisa.xuatnhapcanh.gov.vn. Fee USD 25. Valid 90 days, multiple entries. Apply at least 3 business days before travel; allow more during peak periods. Visa on arrival requires pre-approval letter and generally only suitable for air travel — eVisa STRONGLY recommended. Passport valid at least 6 months with at least 2 blank pages. Return ticket may be requested. Proof of accommodation and funds may be requested. eVisa straightforward online application, approved within 3 business days. Arrival smooth at Noi Bai (Hanoi), Tan Son Nhat (Ho Chi Minh City), Da Nang, and all major ports. Vietnam does not grant visa-free access to Austrian or EU passport holders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'austria' AND destination_slug = 'vietnam';
