/*
  # Update Argentina Passport Complete Visa Requirements

  1. Updates for Argentina Passport Holders
    - Fix all destination visa requirements with accurate, fact-checked data
    - Correct insurance requirements (not mandatory at border for visa-free Schengen)
    - Correct return ticket requirements (may be requested at discretion)
    - Add ETIAS information for all Schengen destinations
    - Add eTA/ESTA/K-ETA/NZeTA requirements where applicable
    - Update notes with comprehensive, accurate entry information
    - Set last_verified to 2026-02-19

  2. Key Corrections
    - Australia: eVisitor/ETA required (not simple visa-free)
    - Canada: Visa required (some eligible for eTA)
    - China: Temporary visa-free until Dec 31, 2026 (15 days only)
    - New Zealand: NZeTA required
    - South Korea: K-ETA required
    - UK: ETA required from April 2, 2025
    - USA: ESTA required under VWP
    - All Schengen: Insurance NOT mandatory at border, return ticket may be requested, ETIAS from late 2026

  3. Affected Destinations
    All 42 destinations for Argentina passport holders
*/

-- Australia
UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'eVisitor or ETA', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Argentine citizens must obtain either a free eVisitor visa (subclass 651) or a paid ETA (subclass 601) before travel. No visa stamp issued on arrival. Max stay: 3 months per visit within a 12-month period. Apply online via Australian Department of Home Affairs before departure. Biometric checks conducted on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'australia';

-- Austria
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport must be valid for at least 3 months beyond departure date and issued within last 10 years. IMPORTANT: ETIAS (European Travel Information and Authorization System) expected to launch late 2026 (€20 fee, valid 3 years). Border officers may request proof of onward travel at their discretion. Travel insurance strongly recommended but not mandatory at border for visa-exempt travelers.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'austria';

-- Belgium
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport must be valid for at least 3 months beyond departure and issued within last 10 years. IMPORTANT: ETIAS expected to launch late 2026 (€20 fee, valid 3 years) and will be mandatory for all Argentine travelers. Border officers may ask for proof of accommodation or onward travel at their discretion. Travel insurance not a formal mandatory entry requirement for visa-exempt travelers.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'belgium';

-- Brazil
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free under Mercosur free movement agreement. Argentine national identity cards (DNI) accepted as travel document. 90 days within any 1-year period for tourism. Mercosur agreement also allows Argentines to live and work legally in Brazil. No mandatory return ticket or proof of funds required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'brazil';

-- Canada
UPDATE visa_rules SET visa_type = 'visa_required', visa_subtype = 'TRV or eTA', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Most Argentine citizens require a Temporary Resident Visa (TRV). However, some who have previously held a Canadian visa or hold a valid US visa may be eligible for an eTA instead. Max stay: up to 6 months per visit. Apply via IRCC at a Canadian visa application centre or online. Eligible travelers may apply for eTA (CAD 7) online. Biometrics required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'canada';

-- Chile
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free under Mercosur bilateral arrangement. Argentine national identity cards (DNI) accepted as travel document. 90 days within any 180-day period. No minimum validity requirement beyond intended stay. Return ticket or proof of funds may be requested at border crossings.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'chile';

-- China
UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'Temporary arrangement', max_stay_days = 15, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'TEMPORARY visa-free arrangement valid from June 1, 2025 to December 31, 2026. 15 days per visit. Outside this window, a full tourist or business visa required. Passport valid at least 6 months beyond entry. Return ticket required. Proof of hotel booking or invitation letter required. Fingerprinting on arrival. Verify arrangement extension before booking.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'china';

-- Colombia
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business visits. 90 days within any 180-day period. Extendable once for additional 90 days at Migración Colombia. Return ticket may be requested by airline or border officers. Proof of sufficient funds may be requested. Yellow fever vaccination certificate required if arriving from endemic country.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'colombia';

-- Croatia
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules (Croatia joined Schengen January 2023). 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure from Schengen Area and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and onward travel may be requested at border officers discretion.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'croatia';

-- Czech Republic
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and return ticket may be requested at border control. Schengen biometric checks apply at external entry points.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'czech-republic';

-- Egypt
UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or e-Visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa on arrival available at major Egyptian international airports. E-Visa also available online at visa2egypt.gov.eg at least 7 days before travel. 30 days per entry. Maximum 3 entries per calendar year and no more than 90 days total within any 1 calendar year. Visa fee USD 25. Return ticket required. Proof of hotel reservation required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'egypt';

-- France
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of sufficient funds and accommodation may be requested. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory at border for visa-exempt travelers.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'france';

-- Germany
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of sufficient funds and accommodation may be verified. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'germany';

-- Greece
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and return ticket may be requested at border officers discretion. Schengen fingerprinting at external border crossings.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'greece';

-- Hungary
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and onward travel may be requested. Schengen biometric checks at external entry points.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'hungary';

-- India
UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'e-Tourist Visa', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'E-Tourist Visa (e-TV) required. Apply online at indianvisaonline.gov.in at least 4 days before arrival and no more than 120 days in advance. 30 days per visit. Maximum 2 e-Tourist Visas per calendar year. Fee USD 25. Passport must have at least 2 blank pages. Must arrive via one of 32 designated airports or 5 seaports. Processing 72-96 hours.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'india';

-- Indonesia
UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'or VoA', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for short tourism stays. 30 days per visit. Extendable once for additional 30 days at local immigration office. Alternatively, Visa on Arrival (IDR 500,000 or approx. USD 30) available at designated airports. Passport must have at least one blank page. Return ticket strongly recommended. Yellow fever certificate if arriving from endemic country. Biometric fingerprinting on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'indonesia';

-- Italy
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and return ticket may be requested. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'italy';

-- Japan
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business visits. 90 days per visit. Persons previously sentenced to 1+ year imprisonment not eligible and must obtain visa. Return ticket required. Proof of sufficient funds and accommodation required. Biometric fingerprinting and photograph on arrival. Departure tax (JPY 1,000) included in airfare.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'japan';

-- Malaysia
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = 365, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. 30 days per visit. Cannot exceed 90 days within any 1-year period. Passport valid at least 6 months. Return ticket or proof of funds may be requested by border officers. Biometric fingerprinting on arrival and departure at all international entry points.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'malaysia';

-- Mexico
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = false, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free for tourism, transit, or short business stays. Up to 180 days for tourism; up to 120 days for business per calendar year. Actual stay granted at immigration officer discretion. Multiple Immigration Form (FMM) required on arrival. FMM free for land entry under 7 days; fee for air travel (included in airfare) or land stays exceeding 7 days.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'mexico';

-- Netherlands
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of sufficient funds and accommodation may be requested. Schengen biometric fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'netherlands';

-- New Zealand
UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'NZeTA', max_stay_days = 90, stay_window_days = null, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Argentina is on NZ visa waiver list but NZeTA (New Zealand Electronic Travel Authority) mandatory before boarding. Not a visa but pre-travel authorization. Apply online or via NZeTA app. Fee NZD 23 (app) or NZD 35 (online). International Visitor Conservation and Tourism Levy (IVL) NZD 35 also applies. Typically approved within 72 hours. Proof of onward travel required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'new-zealand';

-- Nigeria
UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'or e-Visa', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral agreement. Up to 90 days per visit. E-Visa also available at portal.immigration.gov.ng if preferred. Return ticket required. Proof of accommodation and sufficient funds may be requested. Biometrics collected on arrival. Yellow fever vaccination certificate (proof of vaccination) required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'nigeria';

-- Philippines
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism. 30 days on arrival. Extendable at Bureau of Immigration to maximum 59 days, and further in monthly increments up to 3 years. Passport valid at least 6 months beyond departure. Return ticket required. Proof of sufficient funds and accommodation required. Yellow fever certificate if arriving from endemic country. Biometric data collected on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'philippines';

-- Poland
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of sufficient funds and accommodation may be requested. Schengen biometric fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'poland';

-- Portugal
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Schengen biometric fingerprinting at external borders. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'portugal';

-- Qatar
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free access since November 2018. Entry granted on arrival. 30 days per visit. Free visa on arrival also available at Hamad International Airport as alternative. Return ticket required. Proof of hotel booking or sufficient funds required. Biometric iris scan and fingerprinting on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'qatar';

-- Russia
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free under bilateral agreement. 90 days within any 180-day period. Registration with local authorities (OVIR or hotel) within 7 business days mandatory. NOTE: Multiple governments maintain elevated travel advisories for Russia due to ongoing conflict in Ukraine. Flight options significantly limited due to airspace restrictions. Biometric data collected on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'russia';

-- Saudi Arabia
UPDATE visa_rules SET visa_type = 'visa_on_arrival', visa_subtype = 'or e-Visa', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 6, return_ticket_required = true, insurance_required = true, sufficient_funds_required = true, notes = 'Saudi tourist visa on arrival at designated entry points or eVisa online at visa.visitsaudi.com. Up to 90 days per year (single or multiple visits combined). Return ticket required. Hotel booking required. Travel insurance required. Biometric iris scanning and fingerprinting on arrival. eVisa valid 1 year, multiple entries. Cost approximately USD 80 (includes mandatory health insurance).', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'saudi-arabia';

-- Singapore
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism or short business stays. 30 days per visit. Extendable at Immigration and Checkpoints Authority (ICA) before authorized stay expires. Return ticket strongly recommended. Proof of funds and accommodation may be requested. Biometric fingerprinting and photo on arrival and departure. Singapore strictly enforces immigration laws. Declaration via SG Arrival Card app before landing.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'singapore';

-- South Africa
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 1, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free for tourism, transit, or short business stays. 30 days per visit. Passport valid at least 1 month beyond departure with minimum 2 blank pages for stamps. Yellow fever vaccination certificate required if arriving from or transiting through endemic country. Return ticket recommended. Biometric enrollment on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'south-africa';

-- South Korea
UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'K-ETA', max_stay_days = 90, stay_window_days = 365, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free but K-ETA (Korea Electronic Travel Authorization) mandatory before travel. Apply at k-eta.go.kr at least 72 hours before departure. Fee KRW 10,000 (approx. USD 7). Valid 3 years for multiple entries. Up to 90 days within any 12-month period. Return ticket required. Proof of funds and accommodation may be requested. Biometric fingerprinting and photo on arrival. Persons with 1+ year imprisonment not eligible.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'south-korea';

-- Spain
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules. Strong cultural and bilateral relationship with Spain. 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 (€20 fee, valid 3 years). Proof of funds, accommodation, and return ticket may be requested. Travel insurance strongly recommended but not mandatory.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'spain';

-- Switzerland
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 3, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under Schengen rules (Switzerland is Schengen member though not EU). 90 days within any 180-day period across entire Schengen Area. Passport valid at least 3 months beyond departure and issued within last 10 years. ETIAS expected late 2026 will apply to Switzerland as Schengen member (€20 fee, valid 3 years). Proof of funds and accommodation may be requested. Schengen biometric fingerprinting at external borders.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'switzerland';

-- Thailand
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free for tourism stays. Entry granted on arrival. 30 days per visit. Extendable once for additional 30 days at local immigration office (THB 1,900 fee). Passport valid at least 6 months. Return ticket expected by immigration. Proof of funds (THB 20,000 per person or 40,000 per family) may be requested. Biometric fingerprinting on arrival. Yellow fever certificate if from endemic country. Thailand Digital Arrival Card (TDAC) may be required.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'thailand';

-- Turkey
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 90, stay_window_days = 180, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = false, notes = 'Visa-free under bilateral agreement for tourism or short business visits. 90 days within any 180-day period. Passport valid at least 6 months. Return ticket not formally required but may be requested. Proof of accommodation may be requested. Biometric data collected on arrival. E-gates available for re-entry at some airports for enrolled travelers.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'turkey';

-- United Arab Emirates
UPDATE visa_rules SET visa_type = 'visa_free', max_stay_days = 30, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free access since May 2017. Visa automatically stamped on arrival at any UAE port of entry. 30 days per visit. Extendable for additional 30 days through GDRFA. Return ticket required. Proof of sufficient funds and hotel booking required. Biometric iris scanning and fingerprinting on arrival at all UAE ports. Free visa issued on arrival.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'united-arab-emirates';

-- United Kingdom
UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'UK ETA', max_stay_days = 180, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'UK Electronic Travel Authorisation (ETA) mandatory from April 2, 2025. Apply via UK ETA app or online at gov.uk/guidance/apply-for-an-electronic-travel-authorisation-eta. Fee GBP 16 (approx. USD 20). Valid 2 years or until passport expiry. Allows multiple entries. Up to 6 months per visit. Return ticket may be requested by border officers. Proof of funds and purpose of visit may be verified. Biometric checks at UK border. Approval within hours to 3 business days.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'united-kingdom';

-- United States
UPDATE visa_rules SET visa_type = 'evisa', visa_subtype = 'ESTA', max_stay_days = 90, stay_window_days = null, passport_validity_months = 0, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'ESTA (Electronic System for Travel Authorization) required under Visa Waiver Program (VWP). Not a visa but mandatory pre-travel authorization. Apply at esta.cbp.dhs.gov at least 72 hours before departure. Fee USD 21. Valid 2 years or until passport expiry. Up to 90 days per visit. Cannot be extended. Passport must be e-passport (biometric chip). Return ticket required. Biometric fingerprinting and photo on arrival. CBP officers conduct entry interviews. CRITICAL: Overstaying even 1 day permanently forfeits ESTA eligibility.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'united-states';

-- Vietnam
UPDATE visa_rules SET visa_type = 'visa_free', visa_subtype = 'or e-Visa', max_stay_days = 90, stay_window_days = null, passport_validity_months = 6, return_ticket_required = true, insurance_required = false, sufficient_funds_required = true, notes = 'Visa-free under bilateral agreement for tourism or short business stays. Up to 90 days per visit. E-Visa (USD 25) also available at evisa.xuatnhapcanh.gov.vn, valid 90 days, multiple entries. Return ticket may be requested by airline or immigration. Proof of accommodation and sufficient funds may be requested. Entry seamless at Noi Bai (Hanoi), Tan Son Nhat (HCMC), Da Nang, and major ports.', last_verified = '2026-02-19', updated_at = now() WHERE passport_slug = 'argentina' AND destination_slug = 'vietnam';
